// Command celprobe evaluates ../conformance.json against the reference CEL
// implementation and writes the verdicts to ../cel-verdicts.json.
//
// It exists so the "what would real CEL do" column of the conformance corpus is
// a machine-produced fact rather than a maintainer's recollection. That
// distinction is the whole point of the corpus: pkg/celmatch is a hand-written
// subset, the operator writing a policy takes their mental model from GitHub's
// OIDC documentation (which describes real CEL), and the failure mode being
// guarded against is precisely someone being confidently wrong about a corner
// of a language they have read about but not run.
//
// It is a separate module, under testdata/, so cel-go is not a dependency of
// cloop. Bringing the reference implementation into the binary would defeat the
// reason the subset exists (see the package doc on why a closed grammar beats a
// large one for a security gate) and would add a substantial dependency to a
// hub that currently needs none of it. The go tool ignores both nested modules
// and testdata directories, so `go build ./...` and `go test ./...` at the
// repository root never see this file.
//
// Usage, from this directory:
//
//	go run .            # report; exits non-zero if ../cel-verdicts.json is stale
//	go run . -update    # rewrite ../cel-verdicts.json
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"

	"cel.dev/cel-go/cel"
	"cel.dev/cel-go/common/types"
	"cel.dev/cel-go/common/types/ref"
)

const (
	corpusPath   = "../conformance.json"
	verdictsPath = "../cel-verdicts.json"
)

// corpus mirrors the hand-authored half of the conformance data.
type corpus struct {
	Claimsets map[string]map[string]any `json:"claimsets"`
	Cases     []struct {
		Group  string `json:"group"`
		Expr   string `json:"expr"`
		Claims string `json:"claims"`
		Note   string `json:"note,omitempty"`
	} `json:"cases"`
}

// verdictFile is the generated half. Keys are Key(group, expr, claims); the
// test in the parent package reads this and refuses to run if a case is
// missing, so adding a case to the corpus forces a re-probe rather than
// silently going unchecked against real CEL.
type verdictFile struct {
	Comment  []string          `json:"_comment"`
	Verdicts map[string]string `json:"verdicts"`
	// Detail records the reference implementation's own message for anything
	// that did not evaluate to a bool. It is not asserted on; it is there so a
	// reviewer can see *why* CEL refused, which is usually the interesting part.
	Detail map[string]string `json:"detail,omitempty"`
}

func key(group, expr, claims string) string {
	return group + "\x1f" + expr + "\x1f" + claims
}

func main() {
	update := flag.Bool("update", false, "rewrite "+verdictsPath)
	flag.Parse()

	raw, err := os.ReadFile(corpusPath)
	if err != nil {
		die("reading corpus: %v", err)
	}
	var c corpus
	if err := json.Unmarshal(raw, &c); err != nil {
		die("parsing corpus: %v", err)
	}

	// The claim sets carry a _note key for the human reader. It must not reach
	// the activation: an expression selecting it would get an answer that the
	// same token in production would not give.
	for _, cs := range c.Claimsets {
		delete(cs, "_note")
	}

	out := verdictFile{
		Comment: []string{
			"GENERATED by pkg/celmatch/testdata/celprobe. Do not edit by hand.",
			"",
			"Each entry is what the reference CEL implementation (cel.dev/cel-go)",
			"does with one (expression, claim set) pair from conformance.json.",
			"This is the ground truth pkg/celmatch is held against: it may be",
			"stricter than this, never more permissive.",
			"",
			"Keys are group\\x1fexpr\\x1fclaims. Regenerate with:",
			"  cd pkg/celmatch/testdata/celprobe && go run . -update",
		},
		Verdicts: map[string]string{},
		Detail:   map[string]string{},
	}

	counts := map[string]int{}
	for _, tc := range c.Cases {
		claims, ok := c.Claimsets[tc.Claims]
		if !ok {
			die("case %q references unknown claim set %q", tc.Expr, tc.Claims)
		}
		verdict, detail := evaluate(tc.Expr, claims)
		k := key(tc.Group, tc.Expr, tc.Claims)
		if prev, dup := out.Verdicts[k]; dup && prev != verdict {
			die("duplicate case %q disagrees with itself", k)
		}
		out.Verdicts[k] = verdict
		if detail != "" {
			out.Detail[k] = detail
		}
		counts[verdict]++
		fmt.Printf("%-12s %-36s %s\n", verdict, tc.Claims, tc.Expr)
	}

	fmt.Printf("\n%d cases:", len(c.Cases))
	for _, v := range sortedKeys(counts) {
		fmt.Printf("  %s=%d", v, counts[v])
	}
	fmt.Println()

	encoded, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		die("encoding verdicts: %v", err)
	}
	encoded = append(encoded, '\n')

	if !*update {
		existing, err := os.ReadFile(verdictsPath)
		if err != nil {
			die("%s is missing; run with -update", verdictsPath)
		}
		if string(existing) != string(encoded) {
			die("%s is stale; run with -update", verdictsPath)
		}
		fmt.Printf("%s is up to date\n", verdictsPath)
		return
	}
	if err := os.WriteFile(verdictsPath, encoded, 0o644); err != nil {
		die("writing verdicts: %v", err)
	}
	fmt.Printf("wrote %s\n", verdictsPath)
}

// evaluate returns one of allow, deny, error, parse_error or non_bool, plus the
// reference implementation's message when there is one.
//
// `assertion` is declared as a dyn rather than a concrete map type on purpose.
// That is how Google's workload identity federation presents it, and it is the
// configuration under which CEL's type errors surface at evaluation time
// instead of at check time -- which is the interesting comparison, because
// pkg/celmatch has no checker and every type question it asks, it asks during
// evaluation.
func evaluate(src string, claims map[string]any) (verdict, detail string) {
	env, err := cel.NewEnv(cel.Variable("assertion", cel.DynType))
	if err != nil {
		return "error", "env: " + err.Error()
	}
	ast, issues := env.Compile(src)
	if issues != nil && issues.Err() != nil {
		return "parse_error", firstLine(issues.Err().Error())
	}
	prg, err := env.Program(ast)
	if err != nil {
		return "parse_error", firstLine(err.Error())
	}
	val, _, err := prg.Eval(map[string]any{"assertion": claims})
	if err != nil {
		return "error", firstLine(err.Error())
	}
	return classify(val)
}

func classify(val ref.Val) (string, string) {
	switch val {
	case types.True:
		return "allow", ""
	case types.False:
		return "deny", ""
	}
	// An expression that yields a non-bool is not a policy. CEL is happy to
	// produce one; the caller is what decides that is unusable, and
	// pkg/celmatch's Eval rejects it explicitly.
	if b, ok := val.Value().(bool); ok {
		if b {
			return "allow", ""
		}
		return "deny", ""
	}
	return "non_bool", fmt.Sprintf("%v", val.Type())
}

func firstLine(s string) string {
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			return s[:i]
		}
	}
	return s
}

func sortedKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func die(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "celprobe: "+format+"\n", args...)
	os.Exit(1)
}
