package ui

// A machine-readable description of the hub's HTTP surface (Task 20257).
//
// The hub registers 140+ routes, each carrying a method and a required
// permission, and none of that was legible from outside the binary: an
// enterprise integrating against a hub read pkg/ui/routes.go. The obvious fix
// — write an OpenAPI document — is the one that rots, because a hand-written
// document beside a route table drifts the first time somebody adds a route
// and does not think about the spec. pkg/apiserver had exactly that shape
// before this task: eight endpoints described by hand, with nothing failing
// when a ninth was registered.
//
// So the document is generated from routeTable() rather than written beside
// it. Everything it states — path, method, required permission, scope,
// whether the route is reachable without authorization — is read off the same
// value registerRoutes wires onto the mux, which means the description cannot
// disagree with the server: there is only one table.
//
// What generation does not give for free is completeness. A route whose
// pattern shape the conversion below mishandled would vanish from the
// document silently, which is why TestOpenAPICoversExactlyTheRouteTable
// asserts the round trip in both directions rather than trusting it. The
// same route data backs docs/reference/http-api.md, generated by
// tests/docs/http_api_test.go from APIRoutes below.

import (
	"encoding/json"
	"net/http"
	"sort"

	"github.com/blechschmidt/cloop/pkg/apidoc"
	"github.com/blechschmidt/cloop/pkg/apierror"
	"github.com/blechschmidt/cloop/pkg/authz"
	"github.com/blechschmidt/cloop/pkg/logger"
	"github.com/blechschmidt/cloop/pkg/oidcauth"
	"github.com/blechschmidt/cloop/pkg/version"
)

// scopeNames maps each scopeKind to the wire string the document uses. A
// switch rather than a slice indexed by the constant: scopeKind is an iota
// and a reordering must not silently relabel every route.
func scopeName(k scopeKind) string {
	switch k {
	case scopeProject:
		return "project"
	case scopeProjectIdx:
		return "project-index"
	case scopeExecutor:
		return "executor"
	default:
		return "global"
	}
}

// apiRoutes converts the route table into the surface description shared with
// pkg/apiserver and the docs generator.
//
// One routeSpec becomes one Route per verb it serves, because that is the
// granularity at which both OpenAPI and the permission model work: a pattern
// declaring MethodPerms genuinely requires different permissions for
// different verbs, and collapsing them would lose the distinction that makes
// /api/goal readable by a viewer and writable only above one.
func (s *Server) apiRoutes() []apidoc.Route {
	var out []apidoc.Route
	for _, rs := range s.routeTable() {
		_, path, _ := splitPattern(rs.Pattern)
		for _, m := range rs.methods() {
			perm := rs.permFor(m)
			out = append(out, apidoc.Route{
				Method: m,
				Path:   path,
				// PermPublic is not a permission, so it is reported
				// through Public and left out of the permission field
				// rather than named as though a role could hold it.
				Permission: publicAware(perm),
				Public:     perm == authz.PermPublic,
				Scope:      scopeName(rs.Scope),
				Subtree:    len(path) > 1 && path[len(path)-1] == '/',
			})
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Path != out[j].Path {
			return out[i].Path < out[j].Path
		}
		return out[i].Method < out[j].Method
	})
	return out
}

// publicAware returns the permission's wire string, or "" for PermPublic.
func publicAware(p authz.Permission) string {
	if p == authz.PermPublic {
		return ""
	}
	return string(p)
}

// APIRoutes describes the hub's HTTP surface.
//
// Exported for the documentation generator in tests/docs, which renders
// docs/reference/http-api.md from this and from pkg/apiserver.APIRoutes so
// the published reference is generated from the route tables rather than
// maintained alongside them.
//
// It builds a zero Server on purpose: the table's handlers are method values,
// which are well-formed without any server state, and the description depends
// on nothing else. A documentation generator must not need a database, a
// project registry, or a listening port.
func APIRoutes() []apidoc.Route {
	return (&Server{}).apiRoutes()
}

// openAPIInfo is the document's metadata, shared by the handler and the tests.
func openAPIInfo() apidoc.Info {
	return apidoc.Info{
		Title:   "cloop hub API",
		Version: version.Build().Version,
		Description: "The HTTP surface of `cloop ui`, generated from the hub's route table.\n\n" +
			"Every operation carries `x-cloop-permission`: the permission a caller must " +
			"hold to reach it, as named in the audit trail and in `/api/me`. " +
			"`x-cloop-scope` names what that permission is evaluated against — a " +
			"project-scoped grant does not satisfy a global-scope route. Operations " +
			"marked `x-cloop-public` are reachable before authorization is evaluated.\n\n" +
			"Request and response bodies are not described: the route table records " +
			"access control, and inventing payload schemas here would reintroduce the " +
			"hand-maintained fiction this document replaces.",
		BearerAuth: true,
		CookieAuth: oidcauth.SessionCookieName,
	}
}

// renderedOpenAPI holds the document, rendered once by registerRoutes.
//
// Rendering it here rather than per request is not (only) an optimization. The
// hub's central guarantee is that no HTTP handler can reach process execution,
// and tests/security/callgraph_test.go proves it statically. routeTable()
// takes a method value for every handler, so anything a handler calls that
// reaches routeTable() appears — to a static call graph, correctly — to reach
// all 150 of them, including the Claude Code login path that shells out. That
// is a false edge at run time, since taking a method value calls nothing, but
// silencing it with an allowlist entry would spend a real security gate on a
// documentation endpoint.
//
// So the table is walked once at startup, off the request path, and the
// handler only copies bytes. The edge is gone because the call is gone.
type renderedOpenAPI struct{ json []byte }

// buildOpenAPI renders and encodes the document. Called from registerRoutes.
func (s *Server) buildOpenAPI() {
	encoded, err := json.Marshal(apidoc.OpenAPI(openAPIInfo(), s.apiRoutes()))
	if err != nil {
		// The document is built from a table fixed at compile time out of
		// strings and bools, so this cannot fail for data reasons. Log
		// rather than panic: a hub that cannot describe itself should
		// still serve the projects it is running.
		s.log().Error(logger.EventSessionStart, 0, "could not render the OpenAPI document",
			map[string]interface{}{"error": err.Error()})
		return
	}
	s.openAPI.Store(&renderedOpenAPI{json: encoded})
}

// handleOpenAPI serves the generated description. GET /api/openapi.json.
func (s *Server) handleOpenAPI(w http.ResponseWriter, r *http.Request) {
	doc := s.openAPI.Load()
	if doc == nil {
		// Only reachable on a Server whose routes were never registered,
		// which has no surface to describe.
		apierror.WriteError(w, apierror.New(apierror.CodeInternal,
			"the API description is not available on this server"))
		return
	}
	w.Header().Set("Content-Type", "application/json")
	// A short write here means the client went away mid-response, which is
	// ordinary and not actionable.
	_, _ = w.Write(doc.json)
}
