package netfilter

import (
	"fmt"
	"strings"
	"unicode/utf8"
)

// nftables.go renders a Policy as an `nft -f` script.
//
// The script is idempotent by construction. It creates the table, deletes it,
// then creates it again with the rules: `add table` on an existing table is a
// no-op, which makes the delete safe on a first run, and the delete makes the
// whole apply atomic — nft commits a -f script as one transaction, so there
// is no instant at which the sandbox is running under half a ruleset.
//
// Both chains default to drop. Egress is the direction that matters — a
// sandbox exfiltrating data or moving laterally is sending, not receiving —
// but a default-deny input chain costs one more chain and removes the
// question of what else on the bridge can reach into the sandbox.

// nftMaxNameLen bounds a table name. The kernel's limit is 256; staying well
// under it leaves room for the family prefix in error messages and keeps a
// generated name readable in `nft list ruleset`.
const nftMaxNameLen = 64

// NftablesOptions select where the ruleset attaches.
type NftablesOptions struct {
	// Table is the inet table to install into. Deleting and recreating this
	// one table is what makes an apply atomic and idempotent, so it must
	// belong to this sandbox alone.
	Table string

	// Bridge, when set, renders the host-side form: a single forward chain
	// that filters only traffic arriving from that interface.
	//
	// This is how a control-plane host firewalls a container without ever
	// entering the container's network namespace. The bridge exists from
	// the moment the runtime creates the network, which is before any
	// workload can join it, so there is no window in which the sandbox is
	// running unfiltered — the ordering problem that makes the obvious
	// "start it, then firewall it" approach unsafe.
	//
	// Empty renders the in-namespace form instead: output, input and
	// forward chains that default to drop, for a filter installed inside
	// the sandbox's own namespace.
	Bridge string
}

// RenderNftables renders the policy as a script for `nft -f -`.
//
// inet rather than ip and ip6 is not a convenience: two families mean two
// rulesets that can drift, and a v6 ruleset an operator forgot is the whole
// firewall bypassed by a AAAA record.
func RenderNftables(p Policy, opts NftablesOptions) (string, error) {
	if err := ValidateNftName(opts.Table); err != nil {
		return "", err
	}
	if opts.Bridge != "" {
		if err := ValidateInterfaceName(opts.Bridge); err != nil {
			return "", err
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# cloop sandbox egress filter — mode %s\n", p.Mode)
	b.WriteString("# Generated by pkg/netfilter. Edits are lost on the next task.\n")
	for _, w := range p.Warnings {
		for _, line := range wrapComment(w, 74) {
			b.WriteString("# WARNING: " + line + "\n")
		}
	}
	b.WriteString("\n")

	// Create-then-delete-then-create: `add table` succeeds whether or not
	// the table exists, so the delete below never fails on a first apply,
	// and nft commits a -f script as one transaction, so there is no
	// instant at which the sandbox runs under half a ruleset.
	fmt.Fprintf(&b, "add table inet %s\n", opts.Table)
	fmt.Fprintf(&b, "delete table inet %s\n", opts.Table)
	fmt.Fprintf(&b, "table inet %s {\n", opts.Table)

	if opts.Bridge != "" {
		renderBridgeChain(&b, p, opts.Bridge)
	} else {
		renderNamespaceChains(&b, p)
	}

	b.WriteString("}\n")
	return b.String(), nil
}

// renderBridgeChain renders the host-side form.
//
// Two hooks, not one, and the second is the whole reason this function is not
// three lines shorter. A packet from the sandbox is routed by the host, and
// the routing decision picks the hook: destinations the host forwards on
// reach the *forward* hook, while destinations that belong to the host
// itself — the bridge gateway, any address bound on any of its interfaces —
// reach the *input* hook instead. A ruleset with only a forward chain
// therefore filters the Internet and leaves the host wide open, which is
// precisely the lateral movement the block set exists to refuse. Both hooks
// get the same rules because the policy is about destinations, and which hook
// a destination lands on is an implementation detail of the host's routing
// table, not a security boundary.
//
// The chain policy is accept, not drop, and that is the other half of the
// safety argument. Base chains on the same hook all run, and a drop in any of
// them kills the packet — so a `policy drop` chain here would take down every
// other container on the host, plus the host's own traffic in the input case.
// Instead each chain returns immediately for traffic that is not ours (return
// from a base chain applies the chain policy, which is accept) and ends with
// an explicit drop that only packets from this sandbox's bridge can reach.
func renderBridgeChain(b *strings.Builder, p Policy, bridge string) {
	// WireOnly: a packet to 127.0.0.1 never leaves the sandbox's namespace,
	// so a loopback allow here would not be harmless clutter — it would read
	// as "this sandbox may reach the host's loopback", which is the opposite
	// of what the filter does.
	wire := p.WireOnly()

	for _, hook := range []string{"forward", "input"} {
		fmt.Fprintf(b, "\tchain %s {\n", hook)
		fmt.Fprintf(b, "\t\ttype filter hook %s priority 0; policy accept;\n", hook)
		fmt.Fprintf(b, "\t\tiifname != %q return comment \"not this sandbox\"\n", bridge)
		// Replies to flows this policy already permitted. Without it every
		// allow rule would need a mirrored inbound counterpart and the
		// filter would be stateless, which for TCP means nothing works.
		b.WriteString("\t\tct state established,related counter accept\n")
		b.WriteString("\t\tct state invalid counter drop\n")
		writeRules(b, wire, "\t\t")
		b.WriteString("\t\tcounter drop comment \"default deny\"\n")
		b.WriteString("\t}\n")
		if hook == "forward" {
			b.WriteString("\n")
		}
	}
}

// renderNamespaceChains renders the in-namespace form: three chains that
// default to drop, because inside the sandbox's own namespace there is no
// other traffic to be careful of.
func renderNamespaceChains(b *strings.Builder, p Policy) {
	b.WriteString("\tchain output {\n")
	b.WriteString("\t\ttype filter hook output priority 0; policy drop;\n")
	b.WriteString("\t\tct state established,related counter accept\n")
	b.WriteString("\t\tct state invalid counter drop\n")
	writeRules(b, p, "\t\t")
	b.WriteString("\t\tcounter comment \"default deny\"\n")
	b.WriteString("\t}\n\n")

	// Inbound: nothing initiates a connection into a sandbox. Loopback is
	// the sandbox talking to itself and has to survive.
	b.WriteString("\tchain input {\n")
	b.WriteString("\t\ttype filter hook input priority 0; policy drop;\n")
	b.WriteString("\t\tct state established,related counter accept\n")
	b.WriteString("\t\tiifname \"lo\" counter accept comment \"sandbox-local loopback\"\n")
	b.WriteString("\t\tcounter comment \"default deny\"\n")
	b.WriteString("\t}\n\n")

	// A sandbox is an endpoint, never a router. If one ever acquires a
	// second interface, this stops it being used as a bridge between two
	// networks the operator kept apart on purpose.
	b.WriteString("\tchain forward {\n")
	b.WriteString("\t\ttype filter hook forward priority 0; policy drop;\n")
	b.WriteString("\t\tcounter comment \"a sandbox does not route\"\n")
	b.WriteString("\t}\n")
}

// writeRules renders the policy's rules at the given indent.
func writeRules(b *strings.Builder, p Policy, indent string) {
	for _, r := range p.Rules {
		line, ok := renderNftRule(r)
		if !ok {
			continue
		}
		b.WriteString(indent + line + "\n")
	}
}

// ValidateInterfaceName checks a kernel interface name.
//
// The name reaches nft as part of a script, so an unchecked one is command
// injection into the host's firewall — and unlike a table name, this one can
// originate from a runtime's output rather than from cloop.
func ValidateInterfaceName(name string) error {
	if name == "" {
		return fmt.Errorf("netfilter: interface name is empty")
	}
	// IFNAMSIZ is 16 including the terminator.
	if len(name) > 15 {
		return fmt.Errorf("netfilter: interface name %q is too long (%d bytes, limit 15)", name, len(name))
	}
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '_' || r == '-' || r == '.':
		default:
			return fmt.Errorf("netfilter: interface name %q contains an invalid character %q", name, r)
		}
	}
	return nil
}

// renderNftRule renders one rule, or reports false when the rule has no
// nftables expression.
func renderNftRule(r Rule) (string, bool) {
	if !r.Prefix.IsValid() {
		return "", false
	}
	var parts []string

	family := "ip"
	if !r.Prefix.Addr().Is4() {
		family = "ip6"
	}
	// A /0 needs no address match, and nft rejects "ip daddr 0.0.0.0/0" on
	// some kernels. Keeping the family word is what stops a v4 rule from
	// also matching v6 traffic in an inet table.
	if r.Prefix.Bits() == 0 {
		parts = append(parts, "meta nfproto "+ipv(family))
	} else {
		parts = append(parts, family+" daddr "+r.Prefix.String())
	}

	if len(r.Ports) > 0 {
		switch r.Proto {
		case ProtoTCP:
			parts = append(parts, "tcp dport "+nftPortSet(r.Ports))
		case ProtoUDP:
			parts = append(parts, "udp dport "+nftPortSet(r.Ports))
		default:
			// th dport reads the transport header generically, so a port
			// restriction still applies to SCTP and friends rather than
			// silently covering only TCP.
			parts = append(parts, "th dport "+nftPortSet(r.Ports))
		}
	} else if r.Proto != ProtoAny {
		parts = append(parts, "meta l4proto "+r.Proto.String())
	}

	parts = append(parts, "counter")
	if r.Verdict == VerdictAllow {
		parts = append(parts, "accept")
	} else {
		parts = append(parts, "drop")
	}
	if r.Reason != "" {
		parts = append(parts, "comment \""+escapeNftComment(r.Reason)+"\"")
	}
	return strings.Join(parts, " "), true
}

// ipv maps the address-family word to the nfproto keyword.
func ipv(family string) string {
	if family == "ip6" {
		return "ipv6"
	}
	return "ipv4"
}

// nftPortSet renders a port list as an nft anonymous set, or as a bare number
// when there is one. `{ 443 }` is legal but reads as a set with one element,
// and these rulesets get read by humans debugging a broken sandbox.
func nftPortSet(ports []uint16) string {
	if len(ports) == 1 {
		return fmt.Sprint(ports[0])
	}
	parts := make([]string, len(ports))
	for i, p := range ports {
		parts[i] = fmt.Sprint(p)
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

// escapeNftComment makes a reason safe inside a double-quoted nft comment.
//
// Reasons are built from operator input — a granted CIDR's reason quotes the
// block-set entry it waives — so this is an injection boundary, not a
// cosmetic one. Rather than escape and hope nft's lexer agrees, drop every
// character that could end the string or the line.
func escapeNftComment(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '"', r == '\\', r == '\n', r == '\r', r == '\x00', r == ';', r == '{', r == '}', r == '#':
			b.WriteRune(' ')
		case r < 0x20 || r == 0x7f:
			b.WriteRune(' ')
		default:
			b.WriteRune(r)
		}
	}
	out := strings.Join(strings.Fields(b.String()), " ")
	// nft's comment limit is 128 bytes; a longer one is rejected and takes
	// the whole transaction with it. Truncating on a rune boundary rather
	// than a byte one matters because this is the sanitiser for untrusted
	// input: a cut through the middle of a multi-byte rune would hand nft
	// invalid UTF-8, and the failure would arrive as a parse error about a
	// ruleset the operator never wrote.
	if len(out) > 120 {
		cut := 117
		for cut > 0 && !utf8.RuneStart(out[cut]) {
			cut--
		}
		out = out[:cut] + "..."
	}
	return out
}

// ValidateNftName checks a table or chain identifier.
//
// The name reaches nft as part of a script, so an unchecked one is command
// injection into the host's firewall. The grammar here is narrower than
// nft's on purpose: cloop generates these names, so anything outside
// [A-Za-z0-9_-] is a bug rather than a use case.
func ValidateNftName(name string) error {
	if name == "" {
		return fmt.Errorf("netfilter: table name is empty")
	}
	if len(name) > nftMaxNameLen {
		return fmt.Errorf("netfilter: table name is too long (%d bytes, limit %d)", len(name), nftMaxNameLen)
	}
	if name[0] == '-' {
		return fmt.Errorf("netfilter: table name %q may not begin with '-'", name)
	}
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '_' || r == '-':
		default:
			return fmt.Errorf("netfilter: table name %q contains an invalid character %q", name, r)
		}
	}
	return nil
}

// wrapComment breaks a warning into comment-width lines without splitting
// words.
func wrapComment(s string, width int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return nil
	}
	var lines []string
	cur := words[0]
	for _, w := range words[1:] {
		if len(cur)+1+len(w) > width {
			lines = append(lines, cur)
			cur = w
			continue
		}
		cur += " " + w
	}
	return append(lines, cur)
}
