-- plan_tasks.pinned — the column pm.Task.Pinned always needed.
--
-- `cloop task pin` has set the field in memory since it shipped, and the
-- dashboard, kanban and TUI all float pinned rows to the top. None of it
-- survived: the cutover to SQLite enumerated this table's columns by hand and
-- `pinned` was not among them, so every pin was dropped by the next Save and
-- read back as false. The feature could not be observed to be broken because
-- its only visible effect was the thing being discarded.
--
-- Task 20299 makes the flag part of the execution order — the queue's top row
-- is what runs next — so it now has to outlive a save.
--
-- Additive, and deliberately shaped to stay that way: NOT NULL with a DEFAULT
-- and no constraint. schema_compat.go admits exactly that form of ADD COLUMN
-- (an older binary enumerates its columns explicitly, so it never selects this
-- one and never inserts it — the default fills in), and refuses anything with
-- UNIQUE / PRIMARY KEY / REFERENCES / CHECK, or NOT NULL without a default.
-- The class is derived from this SQL, never declared, and
-- TestTaskPinsMigrationIsAdditive asserts the verdict: a breaking migration
-- here would make every older hub sharing these databases refuse to open them,
-- which is the 2026-09-14 outage that file was written to stop.
ALTER TABLE plan_tasks ADD COLUMN pinned INTEGER NOT NULL DEFAULT 0;
