# Outputs.
#
# The set is chosen so that "what do I now paste where" has an answer that is
# not "read the Azure portal". cloop_config_yaml is the paste-in artifact;
# everything else is either a field of it or something an operator needs when
# the sign-in does not work.

locals {
  # Role mappings for the four app roles, plus whatever the caller appended.
  #
  # `claim: role` is Entra's `roles` claim, which carries app role values
  # verbatim. cloop compares these case-insensitively.
  app_role_mappings = [
    for role, _ in local.app_roles :
    "      - {claim: role, value: ${jsonencode(role)}, role: ${role}}"
  ]

  extra_role_mappings = [
    for m in var.cloop_extra_role_mappings :
    format(
      "      - {claim: %s, value: %s, role: %s%s%s}",
      m.claim,
      jsonencode(m.value),
      m.role,
      try(m.project, null) == null ? "" : ", project: ${jsonencode(m.project)}",
      try(m.executor, null) == null ? "" : ", executor: ${jsonencode(m.executor)}",
    )
  ]

  admin_email_lines = length(var.cloop_admin_emails) == 0 ? [] : concat(
    ["    admin_emails:"],
    [for e in var.cloop_admin_emails : "      - ${jsonencode(e)}"],
  )

  # The block an operator merges into .cloop/config.yaml.
  #
  # The client secret is deliberately absent. cloop reads
  # CLOOP_OIDC_CLIENT_SECRET in preference to the YAML field
  # (config.EnvOIDCClientSecret), which is how `cloop hub bootstrap` and the
  # evaluation stack already do it — so the config file stays free of
  # credentials and can be committed, templated, or put in a ConfigMap.
  cloop_config_yaml = join("\n", concat(
    [
      "# Generated by the cloop azure-entra-id Terraform module.",
      "# Merge into .cloop/config.yaml; supply the secret out of band:",
      "#   export CLOOP_OIDC_CLIENT_SECRET=$(terraform output -raw client_secret)",
      "ui:",
      "  external_url: ${jsonencode(var.hub_base_urls[0])}",
      "  oidc:",
      "    enabled: true",
      "    issuer: ${jsonencode(local.issuer)}",
      "    client_id: ${jsonencode(azuread_application.cloop.client_id)}",
      "    redirect_url: ${jsonencode("${var.hub_base_urls[0]}${local.callback_path}")}",
      "",
      "    # offline_access is not optional here. Entra issues a refresh token",
      "    # only when it is asked for, and without one cloop cannot re-ask the",
      "    # IdP whether a user is still valid: session revalidation and the",
      "    # claim-freshness gate on privileged actions both go dark, leaving",
      "    # the two timeouts as the only way a session ever ends.",
      "    scopes: [openid, profile, email, offline_access]",
      "",
      "    # Deny by default: an authenticated user who holds no app role",
      "    # matches nothing below and can read nothing.",
      "    default_role: ${var.cloop_default_role}",
      "",
      "    # Uncomment where a hub that cannot reach Entra should fail to start",
      "    # rather than serve: true in a Kubernetes rollout, where a pod that",
      "    # never becomes ready is rolled back; false on a single VM, where it",
      "    # turns a login outage into a total one.",
      "    # require_idp: true",
      "",
      "    # Entra's `roles` claim carries app role assignments verbatim.",
      "    role_mappings:",
    ],
    local.app_role_mappings,
    local.extra_role_mappings,
    local.admin_email_lines,
    [""],
  ))
}

output "cloop_config_yaml" {
  description = "The ui.oidc block to merge into the hub's .cloop/config.yaml. Contains no secret: cloop reads CLOOP_OIDC_CLIENT_SECRET in preference to the YAML field."
  value       = local.cloop_config_yaml
}

output "client_id" {
  description = "Application (client) ID — ui.oidc.client_id."
  value       = azuread_application.cloop.client_id
}

output "client_secret" {
  description = "Generated client secret — export as CLOOP_OIDC_CLIENT_SECRET. Null when create_client_secret is false."
  value       = try(azuread_application_password.cloop[0].value, null)
  sensitive   = true
}

output "client_secret_expires_at" {
  description = "When the client secret stops working (RFC 3339). Put it in a calendar; a hub whose secret expired fails every sign-in with AADSTS7000222 and serves existing sessions until they time out, so the outage arrives gradually."
  value       = try(azuread_application_password.cloop[0].end_date, null)
}

output "issuer" {
  description = "ui.oidc.issuer. The /v2.0 suffix is required: the v1.0 endpoint issues tokens whose iss is https://sts.windows.net/<tenant>/ and cloop would reject every one of them."
  value       = local.issuer
}

output "discovery_url" {
  description = "The OpenID configuration document cloop's startup preflight fetches. Curl it to distinguish a network problem from a wrong issuer before blaming cloop."
  value       = local.discovery_url
}

output "redirect_url" {
  description = "ui.oidc.redirect_url for the first hub base URL."
  value       = "${var.hub_base_urls[0]}${local.callback_path}"
}

output "redirect_uris" {
  description = "Every redirect URI registered on the application, including each hub's bare origin — which is registered because Entra only honours a post-logout redirect that appears in this list."
  value       = local.redirect_uris
}

output "tenant_id" {
  description = "Directory (tenant) ID the application was created in."
  value       = local.tenant_id
}

output "application_object_id" {
  description = "Object ID of the application registration, for scripts that call Microsoft Graph against it."
  value       = azuread_application.cloop.object_id
}

output "service_principal_object_id" {
  description = "Object ID of the enterprise application. This — not the application object — is what app role assignments and Conditional Access policies attach to."
  value       = azuread_service_principal.cloop.object_id
}

output "app_role_ids" {
  description = "cloop role name to Entra app role ID. Derived with uuidv5 from the role name, so these are identical in every tenant."
  value       = local.app_role_ids
}

output "admin_consent_url" {
  description = "Open this as a Privileged Role Administrator to grant tenant-wide consent for the delegated Graph scopes. Without consent each user is prompted individually on first sign-in, and offline_access is the one users most often decline — which disables IdP revocation for them alone."
  value       = "https://login.microsoftonline.com/${local.tenant_id}/adminconsent?client_id=${azuread_application.cloop.client_id}"
}

output "app_role_assignment_required" {
  description = "Whether Entra refuses a token to users holding no app role. True means an unassigned user is stopped with AADSTS50105 instead of reaching an empty dashboard."
  value       = azuread_service_principal.cloop.app_role_assignment_required
}
