package install

// bootstrap.go renders the script the hub serves at GET /install.sh.
//
// The script is deliberately thin. It does not know how to write a unit file,
// what to harden, or where a credential belongs — all of that lives in the
// cloop binary, where it is versioned with the agent it configures and covered
// by this package's tests. The script's whole job is to get a cloop binary onto
// the device and hand off to `cloop executor agent install`.
//
// That split is what keeps `curl … | sh` defensible. A fat installer piped
// into a shell is a large, unreviewable, unversioned program running as root;
// a thin one is a page an operator can actually read before running it. The
// interesting security properties (0600 credential, no token in argv, hardened
// unit) are enforced by the binary either way, so a tampered script cannot
// weaken them without being obviously different from the one printed in the
// dashboard.
//
// The hub URL and the SPKI pin are interpolated at serve time by the handler
// in pkg/ui, from the request that asked for the script. Pinning matters most
// here: this is the moment a device first learns which control plane to trust,
// and it is the moment an attacker who controls DNS most wants to be believed.

import (
	"fmt"
	"strings"

	"github.com/blechschmidt/cloop/pkg/provenance"
)

// BootstrapParams are the deployment-specific values baked into the script.
type BootstrapParams struct {
	// Server is the WebSocket URL agents dial, e.g.
	// wss://cloop.example.com/api/executors/connect.
	Server string
	// Pin is the hub's SPKI fingerprint, or "" when the hub has no
	// configured certificate. An empty pin makes the script say so rather
	// than quietly install an unpinned agent.
	Pin string
	// ServiceName overrides the installed unit's name.
	ServiceName string
}

// BootstrapScript renders the /install.sh body.
func BootstrapScript(p BootstrapParams) string {
	name := strings.TrimSpace(p.ServiceName)
	if name == "" {
		name = DefaultServiceName
	}

	var b strings.Builder
	b.WriteString(`#!/bin/sh
# cloop executor agent bootstrap.
#
# Generated by the control plane below. It installs a hardened, restart-on-boot
# cloop executor agent on THIS device and enrolls it against that control
# plane. It writes:
#
#   /etc/systemd/system/` + name + `.service   (world-readable, no credential)
#   /var/lib/` + name + `/enrollment           (mode 0600, service user only)
#
# Usage:
#
#   CLOOP_ENROLL_BUNDLE='cloopenroll1.…' sh -c "$(curl -fsSL <url>)"
#
# The bundle is read from the environment, not from an argument, so the
# enrollment token never appears in this device's process list.
set -eu

`)

	fmt.Fprintf(&b, "CLOOP_SERVER=%s\n", shellQuote(p.Server))
	fmt.Fprintf(&b, "CLOOP_PIN=%s\n", shellQuote(strings.TrimSpace(p.Pin)))
	fmt.Fprintf(&b, "CLOOP_SERVICE_NAME=%s\n", shellQuote(name))
	b.WriteString(`CLOOP_RELEASES=${CLOOP_RELEASES:-https://github.com/blechschmidt/cloop/releases/latest/download}
CLOOP_INSECURE_SKIP_VERIFY=${CLOOP_INSECURE_SKIP_VERIFY:-0}
`)

	// Interpolated from the Go constants rather than written out here, so the
	// script and pkg/provenance cannot drift into pinning different things.
	// A script that pinned a stale identity would fail every install the day
	// the workflow moved, and — far worse — one that pinned a looser identity
	// than the Go path would be a quiet downgrade on the entry point that runs
	// as root on a device that has no cloop on it yet.
	fmt.Fprintf(&b, "CLOOP_PROVENANCE_ISSUER=${%s:-%s}\n",
		provenance.IssuerEnv, shellQuote(provenance.DefaultIssuer))
	fmt.Fprintf(&b, "CLOOP_PROVENANCE_IDENTITY=${%s:-%s}\n",
		provenance.IdentityEnv, shellQuote(provenance.DefaultIdentityRegexp))

	b.WriteString(`

# Everything is inside a function invoked on the last line, so a `)
	b.WriteString("`curl | sh`\n")
	b.WriteString(`# that is truncated mid-transfer runs nothing at all instead of running half
# an installer as root.
main() {
  bundle=${CLOOP_ENROLL_BUNDLE:-}
  action=install

  # Arguments are parsed before the privilege check so --help works for
  # someone reading the script before deciding to run it as root — which is
  # exactly the reader this script wants to encourage.
  #
  # An argument form of the bundle is accepted for provisioning systems that
  # cannot set an environment variable, with the caveat stated plainly.
  while [ $# -gt 0 ]; do
    case "$1" in
      --bundle) bundle=${2:-}; shift; [ $# -gt 0 ] && shift || true ;;
      --bundle=*) bundle=${1#--bundle=}; shift ;;
      --service-name) CLOOP_SERVICE_NAME=${2:-}; shift; [ $# -gt 0 ] && shift || true ;;
      --service-name=*) CLOOP_SERVICE_NAME=${1#--service-name=}; shift ;;
      --uninstall) action=uninstall; shift ;;
      --insecure-skip-verify) CLOOP_INSECURE_SKIP_VERIFY=1; shift ;;
      -h|--help) usage; return 0 ;;
      *) die "unknown option: $1" ;;
    esac
  done

  [ "$(id -u)" = "0" ] || die "run this as root (pipe it to 'sudo sh', or re-run under sudo)"

  if [ "$action" = "uninstall" ]; then
    uninstall
    return 0
  fi
  [ -n "$bundle" ] || die "no enrollment bundle. Set CLOOP_ENROLL_BUNDLE, or pass --bundle."

  if [ -z "$CLOOP_PIN" ]; then
    warn "this control plane published no certificate pin."
    warn "the agent will verify it against the system trust store only."
  fi

  bin=$(find_or_fetch_cloop)
  say "using $bin"

  # The bundle is passed on stdin, not as an argument: an argument is visible
  # in /proc to every local user for as long as the installer runs.
  printf '%s\n' "$bundle" | "$bin" executor agent install \
    --output systemd \
    --service-name "$CLOOP_SERVICE_NAME" \
    --server "$CLOOP_SERVER" \
    ${CLOOP_PIN:+--pin "$CLOOP_PIN"} \
    --bundle-stdin

  say "done. Follow the agent with: journalctl -fu ${CLOOP_SERVICE_NAME}.service"
}

uninstall() {
  bin=$(command -v cloop 2>/dev/null || echo /usr/local/bin/cloop)
  [ -x "$bin" ] || die "cloop binary not found; nothing to uninstall"
  "$bin" executor agent install --uninstall --purge --service-name "$CLOOP_SERVICE_NAME"
}

usage() {
  cat <<EOF
cloop executor agent bootstrap

  CLOOP_ENROLL_BUNDLE=<bundle> sh install.sh [--service-name NAME]
  sh install.sh --uninstall [--service-name NAME]

Options:
  --service-name NAME      unit, container and state directory name
  --bundle BUNDLE          enrollment bundle (prefer CLOOP_ENROLL_BUNDLE)
  --uninstall              remove a previous install
  --insecure-skip-verify   install without checking the download's signature.
                           For air-gapped mirrors that cannot reach Sigstore.
                           This gives up the proof that the binary came from
                           cloop's release workflow; the checksum that remains
                           is served from the same place as the archive and so
                           proves only that the download arrived intact.

Environment:
  CLOOP_ENROLL_BUNDLE          enrollment bundle from the hub's Executors panel
  CLOOP_BIN                    use this cloop binary instead of downloading one
  CLOOP_RELEASES               base URL for release downloads
  CLOOP_INSECURE_SKIP_VERIFY   set to 1, same as --insecure-skip-verify
  CLOOP_PROVENANCE_ISSUER      OIDC issuer to require (default: GitHub Actions)
  CLOOP_PROVENANCE_IDENTITY    signing identity regexp to require, for a fork
                               that builds and signs cloop itself

Verify a downloaded archive by hand:
  cosign verify-blob cloop_linux_amd64.tar.gz \\
    --bundle cloop_linux_amd64.tar.gz.sigstore.json \\
    --certificate-oidc-issuer "\$CLOOP_PROVENANCE_ISSUER" \\
    --certificate-identity-regexp "\$CLOOP_PROVENANCE_IDENTITY"
EOF
}

# find_or_fetch_cloop prefers a binary already on the device: an operator who
# has pinned a version, or built one, should not have it replaced by a download
# behind their back.
find_or_fetch_cloop() {
  if [ -n "${CLOOP_BIN:-}" ]; then
    [ -x "$CLOOP_BIN" ] || die "CLOOP_BIN=$CLOOP_BIN is not executable"
    echo "$CLOOP_BIN"
    return
  fi
  for candidate in "$(command -v cloop 2>/dev/null || true)" /usr/local/bin/cloop /usr/bin/cloop; do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
      echo "$candidate"
      return
    fi
  done
  fetch_cloop
}

fetch_cloop() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    armv7l|armv7|armhf) arch=arm ;;
    *) die "unsupported architecture $(uname -m). Install the cloop binary manually and re-run." ;;
  esac
  # The asset name carries no version, because this URL must stay valid across
  # releases: /releases/latest/download/ resolves a fixed name against whatever
  # release is current. scripts/build-release.sh publishes exactly these names
  # and its tests fail if the two ever disagree.
  name="cloop_${os}_${arch}.tar.gz"
  url="$CLOOP_RELEASES/$name"
  tmp=$(mktemp -d)
  # The trap fires on the error paths too, so a failed download does not leave
  # a half-extracted binary in /tmp for the next run to find.
  trap 'rm -rf "$tmp"' EXIT INT TERM
  say "downloading $url"
  download "$url" "$tmp/cloop.tar.gz" || die "download failed: $url"
  # Provenance first, then integrity. The order is not arbitrary: the signature
  # is the check that can actually fail in an attacker's presence, so it should
  # be the one that runs before anything else has had a chance to go wrong. The
  # checksum that follows is a second opinion, not the gate.
  verify_signature "$tmp/cloop.tar.gz" "$name" "$tmp"
  verify_archive "$tmp/cloop.tar.gz" "$name" "$tmp"
  tar -xzf "$tmp/cloop.tar.gz" -C "$tmp" || die "could not extract $url"
  [ -f "$tmp/cloop" ] || die "the release archive did not contain a cloop binary"
  install -m 0755 "$tmp/cloop" /usr/local/bin/cloop || die "could not install /usr/local/bin/cloop"
  echo /usr/local/bin/cloop
}

download() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$1" -o "$2"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$2" "$1"
  else
    die "neither curl nor wget is available; install the cloop binary manually and re-run"
  fi
}

# verify_signature proves the artifact was produced by cloop's release
# workflow, which is the question verify_archive below cannot answer.
#
# checksums.txt is served from the same GitHub release as the archive it
# vouches for. Whoever can replace one can replace the other, and the checksum
# comparison then succeeds against the attacker's own list — it proves the
# bytes arrived intact, never where they came from. The signature is the part
# that cannot be forged without being able to run the release workflow itself.
#
# What is pinned is the OIDC issuer and the signing identity, and both are
# needed. The issuer alone would accept any identity GitHub will mint a token
# for; the identity alone could be asserted by any issuer Fulcio federates
# with. Together they say: signed by this repository's release workflow,
# running on a tag.
#
# A missing cosign is a refusal, not a skip. The tempting alternative — warn
# and continue, as the checksum path does when no sha256sum exists — would
# make every install report success while verifying nothing, and the
# misconfiguration would be invisible precisely because it looks like it
# worked. An operator who cannot install cosign has --insecure-skip-verify,
# which leaves a record of the decision in the command line.
#
# Every variable here is prefixed vs_ because POSIX sh has no locals: a bare
# "name=" would be the *caller's* name. verify_archive calls this function
# while holding the archive's name in exactly that variable, so unprefixed
# assignments silently rewrote it and the checksum was then looked up for
# "checksums.txt" instead of for the artifact. The prefix is the fix, and the
# reason it is worth a comment is that the symptom appeared two functions away
# from the cause.
verify_signature() {
  vs_artifact=$1 vs_name=$2 vs_dir=$3

  if [ "$CLOOP_INSECURE_SKIP_VERIFY" = "1" ]; then
    warn "provenance verification is DISABLED (--insecure-skip-verify):"
    warn "the origin of $vs_name has NOT been checked."
    return 0
  fi

  command -v cosign >/dev/null 2>&1 || die \
    "cosign is required to verify the provenance of $vs_name, and is not installed. \
Install it from https://github.com/sigstore/cosign/releases, or re-run with \
--insecure-skip-verify (or CLOOP_INSECURE_SKIP_VERIFY=1) to install without \
checking where this binary came from."

  vs_sig="$vs_dir/$vs_name.sigstore.json"
  download "$CLOOP_RELEASES/$vs_name.sigstore.json" "$vs_sig" || die \
    "could not download $CLOOP_RELEASES/$vs_name.sigstore.json. Every cloop release \
publishes a signature bundle beside each artifact; if this 404s, the archive \
did not come from a cloop release."

  # cosign's own message names the actual mismatch, and the operator needs it:
  # a wrong identity and a corrupted download have entirely different remedies.
  if ! vs_out=$(cosign verify-blob "$vs_artifact" \
      --bundle "$vs_sig" \
      --certificate-oidc-issuer "$CLOOP_PROVENANCE_ISSUER" \
      --certificate-identity-regexp "$CLOOP_PROVENANCE_IDENTITY" 2>&1); then
    die "SIGNATURE VERIFICATION FAILED for $vs_name. Refusing to install. \
This archive was not signed by cloop's release workflow, which means it is not \
a cloop release — regardless of what its checksum says. cosign reported: $vs_out"
  fi

  say "verified the signature on $vs_name"
}

# verify_archive checks the download against the release's own checksums.txt.
#
# This archive is unpacked as root and installed root-owned and
# world-executable into /usr/local/bin, on a machine that is about to be handed
# credentials. TLS authenticates the transport and nothing else; checksums.txt
# is published beside the artifact precisely so the content can be checked too,
# and a verification that is available but skipped is not a defence.
#
# It fails closed: a mismatch, a missing checksums.txt, or an artifact absent
# from it all abort the install. An operator who wants to supply their own
# binary already has CLOOP_BIN, which skips this path entirely — so failing
# closed here costs nothing but an explicit decision.
verify_archive() {
  archive=$1 name=$2 dir=$3

  if command -v sha256sum >/dev/null 2>&1; then
    actual=$(sha256sum "$archive" | cut -d' ' -f1)
  elif command -v shasum >/dev/null 2>&1; then
    actual=$(shasum -a 256 "$archive" | cut -d' ' -f1)
  else
    # Nothing to verify with. Warn rather than abort: on a system this
    # stripped down there is no second opinion to be had, and refusing would
    # only push the operator towards an unverified manual download.
    warn "no sha256sum or shasum available; cannot verify $name"
    return 0
  fi

  download "$CLOOP_RELEASES/checksums.txt" "$dir/checksums.txt" ||
    die "could not download $CLOOP_RELEASES/checksums.txt to verify $name"

  # The list is signed too. Without this the checksum below would be a
  # comparison against an unauthenticated file — which is the whole reason the
  # signature work exists, reintroduced one level down.
  verify_signature "$dir/checksums.txt" "checksums.txt" "$dir"

  # checksums.txt is GNU format: "<hex>  <filename>". Match the exact name so
  # a substring like cloop_linux_arm.tar.gz cannot satisfy cloop_linux_arm64.
  expected=$(awk -v n="$name" '$2 == n { print $1; exit }' "$dir/checksums.txt")
  [ -n "$expected" ] || die "$name is not listed in checksums.txt"

  [ "$actual" = "$expected" ] || die \
    "checksum mismatch for $name: expected $expected, got $actual. \
Refusing to install. This means the download was corrupted or tampered with."

  say "verified $name (sha256 $actual)"
}

# All three write to stderr, and say() must: find_or_fetch_cloop returns the
# binary path to its caller through a command substitution, so anything else
# written to stdout inside it is concatenated into that path and then executed
# as a single word. The script has no stdout output that is data, so stderr is
# the right destination for all of it regardless.
say()  { printf '\033[36m==>\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[33m==> warning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m==> error:\033[0m %s\n' "$*" >&2; exit 1; }

main "$@"
`)
	return b.String()
}
