package install

// bootstrap.go renders the script the hub serves at GET /install.sh.
//
// The script is deliberately thin. It does not know how to write a unit file,
// what to harden, or where a credential belongs — all of that lives in the
// cloop binary, where it is versioned with the agent it configures and covered
// by this package's tests. The script's whole job is to get a cloop binary onto
// the device and hand off to `cloop executor agent install`.
//
// That split is what keeps `curl … | sh` defensible. A fat installer piped
// into a shell is a large, unreviewable, unversioned program running as root;
// a thin one is a page an operator can actually read before running it. The
// interesting security properties (0600 credential, no token in argv, hardened
// unit) are enforced by the binary either way, so a tampered script cannot
// weaken them without being obviously different from the one printed in the
// dashboard.
//
// The hub URL and the SPKI pin are interpolated at serve time by the handler
// in pkg/ui, from the request that asked for the script. Pinning matters most
// here: this is the moment a device first learns which control plane to trust,
// and it is the moment an attacker who controls DNS most wants to be believed.

import (
	"fmt"
	"strings"
)

// BootstrapParams are the deployment-specific values baked into the script.
type BootstrapParams struct {
	// Server is the WebSocket URL agents dial, e.g.
	// wss://cloop.example.com/api/executors/connect.
	Server string
	// Pin is the hub's SPKI fingerprint, or "" when the hub has no
	// configured certificate. An empty pin makes the script say so rather
	// than quietly install an unpinned agent.
	Pin string
	// ServiceName overrides the installed unit's name.
	ServiceName string
}

// BootstrapScript renders the /install.sh body.
func BootstrapScript(p BootstrapParams) string {
	name := strings.TrimSpace(p.ServiceName)
	if name == "" {
		name = DefaultServiceName
	}

	var b strings.Builder
	b.WriteString(`#!/bin/sh
# cloop executor agent bootstrap.
#
# Generated by the control plane below. It installs a hardened, restart-on-boot
# cloop executor agent on THIS device and enrolls it against that control
# plane. It writes:
#
#   /etc/systemd/system/` + name + `.service   (world-readable, no credential)
#   /var/lib/` + name + `/enrollment           (mode 0600, service user only)
#
# Usage:
#
#   CLOOP_ENROLL_BUNDLE='cloopenroll1.…' sh -c "$(curl -fsSL <url>)"
#
# The bundle is read from the environment, not from an argument, so the
# enrollment token never appears in this device's process list.
set -eu

`)

	fmt.Fprintf(&b, "CLOOP_SERVER=%s\n", shellQuote(p.Server))
	fmt.Fprintf(&b, "CLOOP_PIN=%s\n", shellQuote(strings.TrimSpace(p.Pin)))
	fmt.Fprintf(&b, "CLOOP_SERVICE_NAME=%s\n", shellQuote(name))
	b.WriteString(`CLOOP_RELEASES=${CLOOP_RELEASES:-https://github.com/blechschmidt/cloop/releases/latest/download}

# Everything is inside a function invoked on the last line, so a `)
	b.WriteString("`curl | sh`\n")
	b.WriteString(`# that is truncated mid-transfer runs nothing at all instead of running half
# an installer as root.
main() {
  bundle=${CLOOP_ENROLL_BUNDLE:-}
  action=install

  # Arguments are parsed before the privilege check so --help works for
  # someone reading the script before deciding to run it as root — which is
  # exactly the reader this script wants to encourage.
  #
  # An argument form of the bundle is accepted for provisioning systems that
  # cannot set an environment variable, with the caveat stated plainly.
  while [ $# -gt 0 ]; do
    case "$1" in
      --bundle) bundle=${2:-}; shift; [ $# -gt 0 ] && shift || true ;;
      --bundle=*) bundle=${1#--bundle=}; shift ;;
      --service-name) CLOOP_SERVICE_NAME=${2:-}; shift; [ $# -gt 0 ] && shift || true ;;
      --service-name=*) CLOOP_SERVICE_NAME=${1#--service-name=}; shift ;;
      --uninstall) action=uninstall; shift ;;
      -h|--help) usage; return 0 ;;
      *) die "unknown option: $1" ;;
    esac
  done

  [ "$(id -u)" = "0" ] || die "run this as root (pipe it to 'sudo sh', or re-run under sudo)"

  if [ "$action" = "uninstall" ]; then
    uninstall
    return 0
  fi
  [ -n "$bundle" ] || die "no enrollment bundle. Set CLOOP_ENROLL_BUNDLE, or pass --bundle."

  if [ -z "$CLOOP_PIN" ]; then
    warn "this control plane published no certificate pin."
    warn "the agent will verify it against the system trust store only."
  fi

  bin=$(find_or_fetch_cloop)
  say "using $bin"

  # The bundle is passed on stdin, not as an argument: an argument is visible
  # in /proc to every local user for as long as the installer runs.
  printf '%s\n' "$bundle" | "$bin" executor agent install \
    --output systemd \
    --service-name "$CLOOP_SERVICE_NAME" \
    --server "$CLOOP_SERVER" \
    ${CLOOP_PIN:+--pin "$CLOOP_PIN"} \
    --bundle-stdin

  say "done. Follow the agent with: journalctl -fu ${CLOOP_SERVICE_NAME}.service"
}

uninstall() {
  bin=$(command -v cloop 2>/dev/null || echo /usr/local/bin/cloop)
  [ -x "$bin" ] || die "cloop binary not found; nothing to uninstall"
  "$bin" executor agent install --uninstall --purge --service-name "$CLOOP_SERVICE_NAME"
}

usage() {
  cat <<EOF
cloop executor agent bootstrap

  CLOOP_ENROLL_BUNDLE=<bundle> sh install.sh [--service-name NAME]
  sh install.sh --uninstall [--service-name NAME]

Environment:
  CLOOP_ENROLL_BUNDLE   enrollment bundle from the hub's Executors panel
  CLOOP_BIN             use this cloop binary instead of downloading one
  CLOOP_RELEASES        base URL for release downloads
EOF
}

# find_or_fetch_cloop prefers a binary already on the device: an operator who
# has pinned a version, or built one, should not have it replaced by a download
# behind their back.
find_or_fetch_cloop() {
  if [ -n "${CLOOP_BIN:-}" ]; then
    [ -x "$CLOOP_BIN" ] || die "CLOOP_BIN=$CLOOP_BIN is not executable"
    echo "$CLOOP_BIN"
    return
  fi
  for candidate in "$(command -v cloop 2>/dev/null || true)" /usr/local/bin/cloop /usr/bin/cloop; do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
      echo "$candidate"
      return
    fi
  done
  fetch_cloop
}

fetch_cloop() {
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    armv7l|armv7|armhf) arch=arm ;;
    *) die "unsupported architecture $(uname -m). Install the cloop binary manually and re-run." ;;
  esac
  url="$CLOOP_RELEASES/cloop_${os}_${arch}.tar.gz"
  tmp=$(mktemp -d)
  # The trap fires on the error paths too, so a failed download does not leave
  # a half-extracted binary in /tmp for the next run to find.
  trap 'rm -rf "$tmp"' EXIT INT TERM
  say "downloading $url"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$tmp/cloop.tar.gz" || die "download failed: $url"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$tmp/cloop.tar.gz" "$url" || die "download failed: $url"
  else
    die "neither curl nor wget is available; install the cloop binary manually and re-run"
  fi
  tar -xzf "$tmp/cloop.tar.gz" -C "$tmp" || die "could not extract $url"
  [ -f "$tmp/cloop" ] || die "the release archive did not contain a cloop binary"
  install -m 0755 "$tmp/cloop" /usr/local/bin/cloop || die "could not install /usr/local/bin/cloop"
  echo /usr/local/bin/cloop
}

say()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m==> warning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31m==> error:\033[0m %s\n' "$*" >&2; exit 1; }

main "$@"
`)
	return b.String()
}
