package install

// remoteupgrade.go is what lets a hardened agent carry out an upgrade the hub
// asked for, and what lets a device follow the edge channel (Task 20376).
//
// # The helper
//
// The Executors panel's Upgrade button and the fleet auto-update policy ask a
// device to upgrade itself, and the agent that receives the request runs as an
// unprivileged system user with ProtectSystem=strict and NoNewPrivileges — the
// unit this package renders. It cannot replace /usr/local/bin/cloop, which is
// root's, and it cannot restart its own unit. Task 20331 ran the installer
// inside the agent anyway, so on every device installed with the defaults the
// button was accepted ("upgrading…") and then failed where nobody looked.
//
// Granting the agent root, or write access to its own binary, would undo the
// unit: a workload running as the agent's user could then replace the binary
// that holds CAP_NET_ADMIN, or anything else. So the privilege lives in a
// separate root unit that does one thing:
//
//	<service>-upgrade.path      watches <state dir>/upgrade-request.json
//	<service>-upgrade.service   root, oneshot: reads the request, deletes it,
//	                            stages the named build from the pinned
//	                            repository, verifies it, installs it
//
// The request names a version, a force flag, a settle time and a reason —
// exactly what the hub's upgrade frame names, and nothing more. It cannot name
// a URL, a file or a signing identity, so whatever can write it (the agent, or
// a workload running as its user) can ask for exactly what the hub can: a
// published release, or — only on a device on the edge channel — a signed
// edge build of a commit on main. The helper decides the channel from systemd's
// view of the agent's unit, not from anything the requester can write.
//
// # The channel
//
// A device follows the stable channel (releases) unless an operator on that
// device puts it on the edge channel. That is a drop-in beside the unit, like
// the packet-filter grant, so an upgrade keeps it and the hub cannot change it:
//
//	[Service]
//	Environment=CLOOP_UPDATE_CHANNEL=edge
//
// The agent reads it at start and reports it in its hello, which is how the hub
// knows what to offer; it refuses an edge target without it, and so does the
// helper. The hub's view is advice. The device's is the decision.

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/blechschmidt/cloop/pkg/provenance"
)

// ChannelEnv is the environment variable the channel drop-in sets, and the
// agent reads.
const ChannelEnv = "CLOOP_UPDATE_CHANNEL"

// channelDropInName sorts after the packet-filter drop-in and before
// override.conf, so an operator's own edit still has the last word.
const channelDropInName = "20-update-channel.conf"

// ChannelDropInPath is where the channel drop-in is written.
func (s Spec) ChannelDropInPath() string { return filepath.Join(s.DropInDir(), channelDropInName) }

// ChannelDropIn renders the drop-in that puts the agent on channel c. Only the
// edge channel has one: the stable channel is the absence of the file.
func ChannelDropIn(s Spec, c provenance.Channel) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — generated by `cloop executor agent install`.\n", channelDropInName)
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Puts %s on the %s update channel. It may then be upgraded, from\n", s.UnitFileName(), c)
	b.WriteString("# the hub's Executors panel or by its auto-update policy, to a signed build\n")
	b.WriteString("# of a commit on main that passed CI — the hub's own build — as well as to a\n")
	b.WriteString("# release. Every build is verified against the edge workflow's signing\n")
	b.WriteString("# identity before it is installed. The hub cannot set or clear this; only\n")
	b.WriteString("# root on this device can.\n")
	b.WriteString("#\n")
	b.WriteString("# Return to releases only with `cloop executor agent install --upgrade --channel stable`.\n")
	b.WriteString("\n[Service]\n")
	fmt.Fprintf(&b, "Environment=%s=%s\n", ChannelEnv, c)
	return b.String()
}

// UpgradeHelperName is the base name of the helper's two units.
func (s Spec) UpgradeHelperName() string { return s.ServiceName + "-upgrade" }

// UpgradeHelperServicePath is the helper's service unit.
func (s Spec) UpgradeHelperServicePath() string {
	return filepath.Join(s.UnitDir, s.UpgradeHelperName()+".service")
}

// UpgradeHelperPathUnitPath is the path unit that starts it.
func (s Spec) UpgradeHelperPathUnitPath() string {
	return filepath.Join(s.UnitDir, s.UpgradeHelperName()+".path")
}

// UpgradeHelperStateDir is the helper's own state directory — systemd's
// StateDirectory for it, where cosign keeps the Sigstore trust root it fetched.
func (s Spec) UpgradeHelperStateDir() string { return filepath.Join(DefaultStateRoot, s.UpgradeHelperName()) }

// UpgradeHelperPathUnitName is the path unit's name, for systemctl.
func (s Spec) UpgradeHelperPathUnitName() string { return s.UpgradeHelperName() + ".path" }

// UpgradeRequestPath is where the agent files a request for the helper.
func (s Spec) UpgradeRequestPath() string { return filepath.Join(s.StateDir, UpgradeRequestFileName) }

// UpgradeRequestFileName is the request's file name in the agent's state dir.
const UpgradeRequestFileName = "upgrade-request.json"

// UpgradeHelperService renders the root oneshot that carries out a request.
func UpgradeHelperService(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s.service — generated by `cloop executor agent install`.\n", s.UpgradeHelperName())
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Carries out an upgrade the hub asked %s for. The agent runs\n", s.UnitFileName())
	b.WriteString("# unprivileged on a read-only filesystem, so it cannot replace its own binary\n")
	fmt.Fprintf(&b, "# or restart itself; it writes the version it was asked for to\n#   %s\n", s.UpgradeRequestPath())
	fmt.Fprintf(&b, "# and %s starts this unit, which runs as root and\n", s.UpgradeHelperPathUnitName())
	b.WriteString("#   - reads the request and deletes it,\n")
	b.WriteString("#   - accepts a published release, or an edge build only if this device is on\n")
	b.WriteString("#     the edge channel (decided by the agent unit's own environment),\n")
	b.WriteString("#   - fetches it from the pinned repository and verifies its signature with\n")
	b.WriteString("#     cosign before anything is executed,\n")
	b.WriteString("#   - installs it with the backup, restart and rollback of\n")
	b.WriteString("#     `cloop executor agent install --upgrade`.\n")
	b.WriteString("# A request names a version and nothing else: no URL, no file, no identity.\n")
	b.WriteString("#\n")
	b.WriteString("# Remove both units with `cloop executor agent install --upgrade --remote-upgrade=false`.\n")
	b.WriteString("\n[Unit]\n")
	fmt.Fprintf(&b, "Description=cloop executor agent upgrade (%s)\n", s.ServiceName)
	b.WriteString("Documentation=https://github.com/blechschmidt/cloop\n")
	b.WriteString("After=network-online.target\nWants=network-online.target\n")
	b.WriteString("\n[Service]\nType=oneshot\n")
	args := []string{
		systemdEscape(s.BinaryPath), "executor", "agent", "install", "--upgrade", "--apply-request",
		"--service-name", systemdEscape(s.ServiceName),
		"--binary", systemdEscape(s.BinaryPath),
		"--state-dir", systemdEscape(s.StateDir),
		"--unit-dir", systemdEscape(s.UnitDir),
	}
	fmt.Fprintf(&b, "ExecStart=%s\n", strings.Join(args, " "))
	b.WriteString("# The download, its verification, the swap, the restart and its settle window.\n")
	b.WriteString("TimeoutStartSec=15min\n")
	fmt.Fprintf(&b, "StateDirectory=%s\nStateDirectoryMode=0700\n", s.UpgradeHelperName())
	b.WriteString("# cosign keeps the Sigstore trust root it fetches under $HOME.\n")
	fmt.Fprintf(&b, "Environment=HOME=%s\n", systemdEscape(s.UpgradeHelperStateDir()))
	b.WriteString("StandardOutput=journal\nStandardError=journal\n")
	fmt.Fprintf(&b, "SyslogIdentifier=%s\n", s.UpgradeHelperName())
	b.WriteString("\n# Root, because it replaces a root-owned binary and restarts a unit — and\n")
	b.WriteString("# otherwise confined: it writes only the binary's directory and the request's.\n")
	b.WriteString("NoNewPrivileges=yes\nPrivateTmp=yes\nProtectHome=yes\nProtectSystem=strict\n")
	fmt.Fprintf(&b, "ReadWritePaths=%s %s\n", systemdEscape(filepath.Dir(s.BinaryPath)), systemdEscape(s.StateDir))
	b.WriteString("ProtectKernelTunables=yes\nProtectKernelModules=yes\nProtectKernelLogs=yes\n")
	b.WriteString("ProtectControlGroups=yes\nProtectClock=yes\nProtectHostname=yes\n")
	b.WriteString("RestrictRealtime=yes\nRestrictSUIDSGID=yes\nLockPersonality=yes\n")
	b.WriteString("RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX\nSystemCallArchitectures=native\n")
	return b.String()
}

// UpgradeHelperPathUnit renders the path unit that starts the helper when a
// request appears.
func UpgradeHelperPathUnit(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — generated by `cloop executor agent install`.\n", s.UpgradeHelperPathUnitName())
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Starts %s.service when %s files an upgrade request.\n", s.UpgradeHelperName(), s.UnitFileName())
	b.WriteString("\n[Unit]\n")
	fmt.Fprintf(&b, "Description=cloop executor agent upgrade requests (%s)\n", s.ServiceName)
	b.WriteString("\n[Path]\n")
	fmt.Fprintf(&b, "PathExists=%s\n", s.UpgradeRequestPath())
	fmt.Fprintf(&b, "Unit=%s.service\n", s.UpgradeHelperName())
	b.WriteString("\n[Install]\nWantedBy=multi-user.target\n")
	return b.String()
}

// ── The request ─────────────────────────────────────────────────────────────

// UpgradeRequest is what an agent files for the helper. It mirrors the upgrade
// frame's payload field for field (remote.UpgradePayload), which is the point:
// it carries no more authority than the frame does.
type UpgradeRequest struct {
	TargetVersion string `json:"target_version"`
	Force         bool   `json:"force,omitempty"`
	SettleSeconds int    `json:"settle_seconds,omitempty"`
	Reason        string `json:"reason,omitempty"`
	RequestedAt   string `json:"requested_at"`
}

// maxRequestBytes bounds what the root helper reads from a file its caller's
// user controls.
const maxRequestBytes = 4096

// RequestMaxAge is how old a request may be and still be carried out. A
// request left behind — by a crash, or a device switched off mid-flight — is
// not an instruction to upgrade at the next boot; the hub asks again.
const RequestMaxAge = 15 * time.Minute

// ErrNoRequest reports that no request was filed.
var ErrNoRequest = errors.New("install: no upgrade request is waiting")

// FileUpgradeRequest writes req where the helper's path unit is watching. It
// writes beside and renames, so the helper never reads half a request.
func FileUpgradeRequest(s Spec, req UpgradeRequest) error {
	if strings.TrimSpace(req.RequestedAt) == "" {
		req.RequestedAt = time.Now().UTC().Format(time.RFC3339)
	}
	data, err := json.Marshal(req)
	if err != nil {
		return err
	}
	dst := s.UpgradeRequestPath()
	tmp, err := os.CreateTemp(filepath.Dir(dst), ".upgrade-request-*")
	if err != nil {
		return fmt.Errorf("install: file the upgrade request: %w", err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("install: file the upgrade request: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("install: file the upgrade request: %w", err)
	}
	if err := os.Rename(tmp.Name(), dst); err != nil {
		return fmt.Errorf("install: file the upgrade request: %w", err)
	}
	return nil
}

// TakeUpgradeRequest reads the waiting request and deletes it, as root, from a
// directory owned by the agent's user.
//
// That directory is the caller's to control, so the read is defensive: the
// file is opened without following a symlink, must be a regular file of a few
// KiB, and is deleted before it is acted on — a request that cannot be parsed
// or is stale is deleted too, so the path unit does not start the helper again
// on the same file. now is the clock, for tests.
func TakeUpgradeRequest(s Spec, now time.Time) (UpgradeRequest, error) {
	var req UpgradeRequest
	path := s.UpgradeRequestPath()
	f, err := os.OpenFile(path, os.O_RDONLY|syscall.O_NOFOLLOW|syscall.O_NONBLOCK, 0)
	if err != nil {
		if os.IsNotExist(err) {
			return req, ErrNoRequest
		}
		_ = os.Remove(path)
		return req, fmt.Errorf("install: open the upgrade request %s: %w", path, err)
	}
	defer f.Close()
	// Gone from the directory before anything else happens, whatever happens.
	_ = os.Remove(path)

	st, err := f.Stat()
	if err != nil {
		return req, fmt.Errorf("install: stat the upgrade request: %w", err)
	}
	if !st.Mode().IsRegular() || st.Size() > maxRequestBytes {
		return req, fmt.Errorf("install: %s is not a request (a %s of %d bytes); ignored", path, st.Mode().Type(), st.Size())
	}
	data, err := io.ReadAll(io.LimitReader(f, maxRequestBytes+1))
	if err != nil {
		return req, fmt.Errorf("install: read the upgrade request: %w", err)
	}
	if err := json.Unmarshal(data, &req); err != nil {
		return req, fmt.Errorf("install: the upgrade request is not JSON: %w", err)
	}
	req.TargetVersion = strings.TrimSpace(req.TargetVersion)
	switch {
	case req.TargetVersion == "":
		return req, fmt.Errorf("install: the upgrade request names no version")
	case req.SettleSeconds < 0 || req.SettleSeconds > 3600:
		return req, fmt.Errorf("install: the upgrade request's settle time %ds is out of range", req.SettleSeconds)
	}
	at, err := time.Parse(time.RFC3339, req.RequestedAt)
	if err != nil {
		return req, fmt.Errorf("install: the upgrade request has no valid requested_at: %w", err)
	}
	if age := now.Sub(at); age > RequestMaxAge {
		return req, fmt.Errorf("install: the upgrade request for %s is %s old (the limit is %s); ignored",
			req.TargetVersion, age.Round(time.Second), RequestMaxAge)
	}
	if len(req.Reason) > 200 {
		req.Reason = req.Reason[:200]
	}
	req.Reason = strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return ' '
		}
		return r
	}, req.Reason)
	return req, nil
}

// ── What the device has decided ────────────────────────────────────────────

// HelperInstalled reports whether the device has the remote-upgrade helper.
func (in *Installer) HelperInstalled(s Spec) bool {
	_, err := os.Stat(in.path(s.UpgradeHelperPathUnitPath()))
	return err == nil
}

// DeviceChannel reports the channel the agent's unit puts it on, as root sees
// it: systemd's merged Environment= for the unit, so an operator's own
// override counts as much as the drop-in this package writes. A staged
// installer, which runs no commands, reads the drop-in directory instead.
//
// It never reads anything the agent's user can write. That is what makes it
// the helper's answer to "may this device install an edge build", rather than
// the request's.
func (in *Installer) DeviceChannel(s Spec) (provenance.Channel, error) {
	if !in.staged() && in.Run == nil {
		out, err := runOutput("systemctl", "show", "--property=Environment", "--value", s.UnitFileName())
		if err != nil {
			return provenance.ChannelStable, fmt.Errorf("install: read %s's environment: %w", s.UnitFileName(), err)
		}
		return channelFromAssignments(strings.Fields(out))
	}
	entries, err := os.ReadDir(in.path(s.DropInDir()))
	if err != nil {
		if os.IsNotExist(err) {
			return provenance.ChannelStable, nil
		}
		return provenance.ChannelStable, err
	}
	var assignments []string
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".conf") {
			continue
		}
		body, err := os.ReadFile(filepath.Join(in.path(s.DropInDir()), e.Name()))
		if err != nil {
			return provenance.ChannelStable, err
		}
		for _, d := range unitDirectives(string(body)) {
			if v, ok := strings.CutPrefix(d, "Environment="); ok {
				assignments = append(assignments, strings.Fields(v)...)
			}
		}
	}
	return channelFromAssignments(assignments)
}

// channelFromAssignments finds the last CLOOP_UPDATE_CHANNEL=... among
// environment assignments, as systemd would apply them.
func channelFromAssignments(assignments []string) (provenance.Channel, error) {
	value := ""
	for _, a := range assignments {
		a = strings.Trim(a, `"'`)
		if v, ok := strings.CutPrefix(a, ChannelEnv+"="); ok {
			value = v
		}
	}
	return provenance.ParseChannel(value)
}

// runOutput runs a command and returns its stdout.
var runOutput = func(name string, args ...string) (string, error) {
	out, err := exec.Command(name, args...).Output()
	return string(out), err
}
