package install

// shell.go is the --output shell rendering: a POSIX init script for devices
// with no systemd and no container engine — BusyBox routers, OpenRC boxes,
// anything running a stripped userspace.
//
// It cannot reproduce systemd's confinement; nothing portable can. What it
// does reproduce is the part that actually loses credentials in the field: the
// script never puts the token on a command line, refuses to run if the
// credential file is group- or world-readable, and re-asserts 0600 on every
// start. It also supervises: an agent that exits is restarted after a short
// delay, so a device that drops off the network comes back without a visit.

import (
	"fmt"
	"path/filepath"
	"strings"
)

// InitScript renders the POSIX supervisor script for spec s.
func InitScript(s Spec) string {
	pidFile := filepath.Join("/run", s.ServiceName+".pid")
	logFile := filepath.Join("/var/log", s.ServiceName+".log")

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# " + s.ServiceName + " — generated by `cloop executor agent install --output shell`.\n")
	b.WriteString("#\n")
	b.WriteString("# The enrollment token is NOT in this script. It lives at the path in\n")
	b.WriteString("# CRED below, mode 0600, and is passed to the agent as a path so it never\n")
	b.WriteString("# appears in `ps` output.\n")
	b.WriteString("#\n")
	b.WriteString("# chkconfig: 2345 90 10\n")
	b.WriteString("# description: cloop remote executor agent\n")
	b.WriteString("### BEGIN INIT INFO\n")
	b.WriteString("# Provides:          " + s.ServiceName + "\n")
	b.WriteString("# Required-Start:    $network $remote_fs\n")
	b.WriteString("# Required-Stop:     $network $remote_fs\n")
	b.WriteString("# Default-Start:     2 3 4 5\n")
	b.WriteString("# Default-Stop:      0 1 6\n")
	b.WriteString("# Short-Description: cloop remote executor agent\n")
	b.WriteString("### END INIT INFO\n")
	b.WriteString("\nset -eu\n\n")

	fmt.Fprintf(&b, "NAME=%s\n", shellQuote(s.ServiceName))
	fmt.Fprintf(&b, "BIN=%s\n", shellQuote(s.BinaryPath))
	fmt.Fprintf(&b, "USER=%s\n", shellQuote(s.User))
	fmt.Fprintf(&b, "STATE=%s\n", shellQuote(s.StateDir))
	fmt.Fprintf(&b, "CRED=%s\n", shellQuote(s.CredentialsFile))
	fmt.Fprintf(&b, "PIDFILE=%s\n", shellQuote(pidFile))
	fmt.Fprintf(&b, "LOGFILE=%s\n", shellQuote(logFile))
	fmt.Fprintf(&b, "RESTART_DELAY=%s\n", "5")
	b.WriteString("\n")

	b.WriteString("ARGS=\"")
	quoted := make([]string, 0, len(s.agentArgs()))
	for _, a := range s.agentArgs() {
		quoted = append(quoted, shellQuote(a))
	}
	b.WriteString(strings.Join(quoted, " "))
	b.WriteString("\"\n\n")

	b.WriteString(`log() { printf '%s %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$*" >&2; }

# check_cred re-asserts 0600 on the enrollment file and says so loudly when it
# had to. It warns rather than refusing, matching the agent's own credential
# loader: bricking a device because a provisioning script ran with the wrong
# umask is a worse outcome than the exposure, and an operator who sees the
# warning can revoke the token. The chmod still closes the window for every
# subsequent start.
check_cred() {
  [ -e "$CRED" ] || return 0
  mode=$(stat -c '%a' "$CRED" 2>/dev/null || stat -f '%Lp' "$CRED" 2>/dev/null || echo '')
  case "$mode" in
    600|0600|400|0400|'') ;;
    *)
      log "$NAME: warning — $CRED was mode $mode; tightening it to 0600."
      log "$NAME: treat that token as exposed: revoke it once this device has enrolled."
      ;;
  esac
  chmod 600 "$CRED" 2>/dev/null || true
  return 0
}

running() {
  [ -f "$PIDFILE" ] || return 1
  pid=$(cat "$PIDFILE" 2>/dev/null || echo '')
  [ -n "$pid" ] || return 1
  kill -0 "$pid" 2>/dev/null
}

# supervise is the restart loop. The agent already reconnects on its own, so
# this only handles the case where the process itself dies.
supervise() {
  while :; do
    if [ "$(id -u)" = '0' ] && [ "$USER" != 'root' ]; then
      su -s /bin/sh -c "HOME=$STATE exec \"\$0\" \$ARGS" "$USER" "$BIN" || true
    else
      HOME="$STATE" "$BIN" $ARGS || true
    fi
    log "$NAME: agent exited; restarting in ${RESTART_DELAY}s"
    sleep "$RESTART_DELAY"
  done
}

start() {
  if running; then log "$NAME: already running"; return 0; fi
  check_cred || return 1
  mkdir -p "$STATE" && chmod 700 "$STATE"
  [ "$(id -u)" = '0' ] && chown -R "$USER" "$STATE" 2>/dev/null || true
  umask 077
  touch "$LOGFILE" 2>/dev/null || true
  supervise >>"$LOGFILE" 2>&1 &
  echo $! > "$PIDFILE"
  log "$NAME: started (pid $(cat "$PIDFILE"))"
}

stop() {
  if ! running; then
    rm -f "$PIDFILE"
    log "$NAME: not running"
    return 0
  fi
  pid=$(cat "$PIDFILE")
  # Kill the supervisor's whole process group so the loop cannot respawn the
  # agent between the two signals.
  kill -TERM "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
  i=0
  while [ "$i" -lt 30 ] && kill -0 "$pid" 2>/dev/null; do
    sleep 1
    i=$((i + 1))
  done
  kill -KILL "-$pid" 2>/dev/null || kill -KILL "$pid" 2>/dev/null || true
  rm -f "$PIDFILE"
  log "$NAME: stopped"
}

status() {
  if running; then
    echo "$NAME: running (pid $(cat "$PIDFILE"))"
    return 0
  fi
  echo "$NAME: stopped"
  return 3
}

case "${1:-}" in
  start)   start ;;
  stop)    stop ;;
  restart) stop; start ;;
  status)  status ;;
  *)       echo "usage: $0 {start|stop|restart|status}" >&2; exit 2 ;;
esac
`)
	return b.String()
}

// shellQuote wraps a value in single quotes when it contains anything a shell
// would interpret. Duplicated from remote.shellQuote rather than exported
// across the package boundary: the two have the same body but different
// owners, and coupling a rendering detail of the installer to the enrollment
// package would make either one harder to change.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	safe := true
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case strings.ContainsRune("-_.:/@+=,", r):
		default:
			safe = false
		}
		if !safe {
			break
		}
	}
	if safe {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
