package install

// systemd.go renders the hardened service unit.
//
// The directive list is not decoration. The agent executes code a control
// plane sends it, which is the definition of a process you assume will one day
// run something you did not intend. The unit's job is to make that day boring:
// the process cannot gain privilege (NoNewPrivileges, empty
// CapabilityBoundingSet), cannot write outside its own state directory
// (ProtectSystem=strict), cannot see other users' data (ProtectHome,
// ProtectProc=invisible), and cannot reach the kernel's tuning surfaces at all.
//
// Everything is emitted in a fixed order so two installs of the same spec
// produce byte-identical units — a config-management system that re-renders
// the unit on every run must not restart the fleet because a map iterated
// differently.

import (
	"fmt"
	"path/filepath"
	"strings"
)

// hardening is the security block, in the order it appears in the unit.
//
// It is a table rather than a heredoc so the reasoning stays attached to the
// directive, and so a future relaxation is a line removed rather than a
// string edited.
var hardening = []struct{ directive, why string }{
	{"NoNewPrivileges=yes",
		"a harness that finds a setuid binary still cannot use it"},
	{"CapabilityBoundingSet=",
		"the agent needs no capability; an empty set means none can be regained"},
	{"AmbientCapabilities=",
		"and none are handed to it at exec"},
	{"ProtectSystem=strict",
		"the entire filesystem is read-only except StateDirectory below"},
	{"ProtectHome=yes",
		"/home, /root and /run/user are invisible — the device's user data is not the agent's business"},
	{"PrivateTmp=yes",
		"a private /tmp, so a workload cannot read another service's scratch files"},
	{"PrivateDevices=yes",
		"only the pseudo-devices; no raw disks, no /dev/kvm"},
	{"ProtectProc=invisible",
		"other users' processes are not listed, so a workload cannot read their argv"},
	{"ProcSubset=pid",
		"and the kernel's /proc tunables are not there to be read either"},
	{"ProtectKernelTunables=yes", ""},
	{"ProtectKernelModules=yes", ""},
	{"ProtectKernelLogs=yes", ""},
	{"ProtectControlGroups=yes", ""},
	{"ProtectClock=yes", ""},
	{"ProtectHostname=yes", ""},
	// systemd names namespace types "user"/"mnt"/…, not by their CLONE_
	// constants; the constant form parses as garbage and is silently ignored,
	// which is the worst possible failure mode for a hardening directive.
	// TestGeneratedUnitPassesSystemdAnalyze is what caught it.
	{"RestrictNamespaces=~user",
		"no user namespaces: the usual first step out of a confined service"},
	{"RestrictRealtime=yes", ""},
	{"RestrictSUIDSGID=yes",
		"a workload cannot create a setuid file to escalate through later"},
	{"RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX",
		"IP and local sockets only; no AF_PACKET, no AF_NETLINK"},
	{"LockPersonality=yes", ""},
	{"SystemCallArchitectures=native", ""},
	{"SystemCallFilter=@system-service",
		"the standard service syscall set; @privileged and @obsolete are not in it"},
	{"SystemCallErrorNumber=EPERM",
		"a blocked call fails the operation rather than killing the process, so the failure is legible in the logs"},
	{"UMask=0077",
		"anything the agent writes is private by default, including the credential it receives at enrollment"},
}

// relaxationNote is emitted as a comment so an operator whose device runs
// container workloads through the agent knows exactly which two lines to drop,
// instead of discovering the constraint as an unexplained runtime failure.
const relaxationNote = `# If this device runs CONTAINER workloads through the agent (rootless podman,
# nested sandboxes), remove PrivateDevices= and RestrictNamespaces= below:
# both are incompatible with user-namespace container runtimes. Leave the rest.`

// SystemdUnit renders the service unit for spec s.
//
// s is expected to have been through Normalize; BuildPlan is the supported
// entry point and does that for you.
func SystemdUnit(s Spec) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s — generated by `cloop executor agent install`.\n", s.UnitFileName())
	b.WriteString("#\n")
	b.WriteString("# The enrollment token is NOT in this file. It lives at\n")
	fmt.Fprintf(&b, "#   %s (mode 0600, owned by %s)\n", s.CredentialsFile, s.User)
	b.WriteString("# and reaches the agent as a path, because a unit file is world-readable\n")
	b.WriteString("# and `systemctl show` prints ExecStart to anyone who asks.\n")
	b.WriteString("#\n")
	b.WriteString("# Re-running the installer overwrites this file. Edits belong in a drop-in:\n")
	fmt.Fprintf(&b, "#   %s.d/override.conf\n", s.UnitPath())
	b.WriteString("\n")

	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=cloop remote executor agent (%s)\n", s.ServiceName)
	b.WriteString("Documentation=https://github.com/blechschmidt/cloop\n")
	// network-online rather than network.target: the agent's first action is
	// an outbound TLS dial, and starting it before DNS resolves just burns a
	// reconnect cycle on every boot.
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n")
	// The agent's own backoff is the retry policy. systemd's rate limiter on
	// top of it would put a device that was offline overnight into a failed
	// state that needs a human, which is the one thing an edge fleet cannot
	// afford.
	b.WriteString("StartLimitIntervalSec=0\n")
	b.WriteString("\n")

	b.WriteString("[Service]\n")
	// Type=exec, not simple: systemd reports a failure if the binary cannot
	// be executed, instead of reporting success and leaving a unit that is
	// "active" with nothing running.
	b.WriteString("Type=exec\n")
	fmt.Fprintf(&b, "User=%s\n", s.User)
	fmt.Fprintf(&b, "Group=%s\n", s.Group)
	fmt.Fprintf(&b, "ExecStart=%s\n", execStartLine(s))
	b.WriteString("Restart=always\n")
	b.WriteString("RestartSec=5s\n")
	// The agent finishes in-flight workloads on SIGTERM; give it room to.
	b.WriteString("TimeoutStopSec=30s\n")
	b.WriteString("KillMode=mixed\n")
	b.WriteString("\n")

	// State. StateDirectory is preferred over a bare path because systemd
	// creates it with the right owner and mode on every start, which
	// survives an operator (or an image build) deleting /var/lib contents.
	// It is only usable when the directory actually lives under /var/lib.
	if name, ok := stateDirectoryName(s.StateDir); ok {
		fmt.Fprintf(&b, "StateDirectory=%s\n", name)
		fmt.Fprintf(&b, "StateDirectoryMode=%04o\n", StateDirMode)
	} else {
		b.WriteString("# StateDir is outside /var/lib, so it is granted explicitly instead of\n")
		b.WriteString("# through StateDirectory=. It must exist and be owned by the service user.\n")
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", systemdEscape(s.StateDir))
	}
	// The workload root is granted separately: it defaults to a subdirectory
	// of StateDir (already writable) but an operator who points it at a
	// scratch disk needs the grant, and a redundant ReadWritePaths is free.
	if !underDir(s.StateDir, s.WorkDirRoot) {
		fmt.Fprintf(&b, "ReadWritePaths=%s\n", systemdEscape(s.WorkDirRoot))
	}
	fmt.Fprintf(&b, "WorkingDirectory=%s\n", systemdEscape(s.StateDir))
	// Tools the harness shells out to (git, npm, the claude CLI) all write
	// into $HOME. Without this they would find the service user's real home
	// — which ProtectHome has just made invisible — and fail obscurely.
	fmt.Fprintf(&b, "Environment=HOME=%s\n", systemdEscape(s.StateDir))
	fmt.Fprintf(&b, "Environment=XDG_CONFIG_HOME=%s\n", systemdEscape(filepath.Join(s.StateDir, ".config")))
	fmt.Fprintf(&b, "Environment=XDG_CACHE_HOME=%s\n", systemdEscape(filepath.Join(s.StateDir, ".cache")))
	b.WriteString("\n")

	// Logs go to the journal. An edge device with no log shipper still has
	// `journalctl -u <unit>`, and one with a shipper picks the journal up
	// without further configuration.
	b.WriteString("StandardOutput=journal\n")
	b.WriteString("StandardError=journal\n")
	fmt.Fprintf(&b, "SyslogIdentifier=%s\n", s.ServiceName)
	b.WriteString("\n")

	b.WriteString("# ── Hardening ──────────────────────────────────────────────────────────\n")
	b.WriteString(relaxationNote)
	b.WriteString("\n")
	for _, h := range hardening {
		if h.why != "" {
			fmt.Fprintf(&b, "# %s\n", h.why)
		}
		b.WriteString(h.directive)
		b.WriteString("\n")
	}
	b.WriteString("\n")

	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}

// execStartLine renders the command line, escaped for a unit file.
func execStartLine(s Spec) string {
	parts := make([]string, 0, 1+len(s.agentArgs()))
	parts = append(parts, systemdEscape(s.BinaryPath))
	for _, a := range s.agentArgs() {
		parts = append(parts, systemdEscape(a))
	}
	return strings.Join(parts, " ")
}

// systemdEscape quotes a value for a unit file directive.
//
// Two distinct hazards: '%' begins a systemd specifier expansion, and
// whitespace splits an argument. A workdir root containing a space would
// otherwise become two arguments, and one containing "%i" would expand to
// something the operator never typed.
func systemdEscape(v string) string {
	escaped := strings.ReplaceAll(v, "%", "%%")
	if v == "" {
		return `""`
	}
	if !strings.ContainsAny(v, " \t\"'\\$;") {
		return escaped
	}
	// Double-quoted form: systemd unescapes \" and \\ inside it.
	q := strings.ReplaceAll(escaped, `\`, `\\`)
	q = strings.ReplaceAll(q, `"`, `\"`)
	return `"` + q + `"`
}

// stateDirectoryName returns the StateDirectory= value for dir when dir is a
// direct child of /var/lib, which is the only shape systemd accepts.
func stateDirectoryName(dir string) (string, bool) {
	clean := filepath.Clean(dir)
	parent, name := filepath.Split(clean)
	if filepath.Clean(parent) != DefaultStateRoot || name == "" {
		return "", false
	}
	// StateDirectory= takes a relative path with no separators of its own.
	if strings.ContainsRune(name, filepath.Separator) {
		return "", false
	}
	return name, true
}

// underDir reports whether child is parent or lies beneath it.
func underDir(parent, child string) bool {
	p := filepath.Clean(parent)
	c := filepath.Clean(child)
	if p == c {
		return true
	}
	rel, err := filepath.Rel(p, c)
	if err != nil {
		return false
	}
	return rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}
