package docs_test

// docs/reference/credential-patterns.md is generated from pkg/redact's
// registry (Task 20368), on the same arrangement as audit-events.md: the page
// is rendered from the detectors themselves, and the checked-in copy is
// compared against a fresh rendering on every run.
//
//	make docs-credentials    # or: go test ./tests/docs -run TestCredentialPatternsReference -update-credentials
//
// The registry is what four scanners share, so the list of what they
// recognise is exactly the kind of enumeration that rots when written by
// hand: a detector added to the code, missing from the page an operator reads
// to decide whether cloop audit would have caught their leak.

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/blechschmidt/cloop/pkg/redact"
)

var updateCredentials = flag.Bool("update-credentials", false, "regenerate docs/reference/credential-patterns.md")

const credentialPatternsPage = "docs/reference/credential-patterns.md"

const credentialPatternsIntro = `# Credential patterns

Every credential shape cloop recognises by pattern, generated from the
registry in ` + "`pkg/redact`" + `. Do not edit this file: it is rendered by
` + "`tests/docs/credential_patterns_test.go`" + `, and a CI check fails when it stops
matching. Regenerate with ` + "`make docs-credentials`" + `.

## Who uses this list

Four scanners handle text whose secrets they cannot know in advance, and all
four ask this registry rather than keeping a list of their own:

| Scanner | What it does with a match |
| --- | --- |
| ` + "`cloop audit`" + ` | reports the detector's label for ` + "`.cloop/`" + ` git history and task artifacts |
| the provider-call audit | stores the error as ` + "`<lead>[REDACTED]`" + ` — ` + "`sk-ant-api03-[REDACTED]`" + ` |
| the secret broker's audit reasons | stores ` + "`[redacted]`" + ` |
| browser telemetry | stores ` + "`[redacted]`" + ` |

Which text each one sees, and what else it applies, is in the
[security model](../security/model.md#what-is-scrubbed-where).

This is not the primary defence. A credential a lease delivered is removed by
its exact value wherever task output is captured, whatever its shape; these
patterns are the backstop for text that never passed through that match.

## How to read the table

The **detector** is a stable name: ` + "`cloop audit`" + ` and the test corpus key on it,
so a detector is retired rather than renamed. **Reported as** is the wording a
finding uses. A finding never includes the value.

Rows are in precedence order. When two detectors claim the same text — a
GitHub token inside an Authorization header inside a URL — the redactors
replace it once, and the detector listed first names the match. ` + "`cloop audit`" + `
reports every detector that matched.

Context a detector needs in order to recognise a credential is kept: ` + "`Bearer `" + `,
a field's key, a URL's scheme and host. Only the credential is replaced, and
a field's value is replaced to the next delimiter, so one that holds
punctuation the detector does not list goes whole.

What documentation prints in a credential's place is not a finding. A
detector that recognises a prefix leaves alone a body that is mostly one
repeated character (` + "`ghp_xxxx…`" + `), and a field detector leaves alone a
value that ends that way (` + "`GITHUB_TOKEN=ghp_xxxx…`" + `) or is a template
(` + "`$TOKEN`" + `, ` + "`${DB_PASSWORD}`" + `).
`

func renderCredentialPatterns() string {
	var b strings.Builder
	b.WriteString(credentialPatternsIntro)
	b.WriteString("\n## Detectors\n\n| Detector | Reported as | Recognises |\n| --- | --- | --- |\n")
	for _, d := range redact.Detectors() {
		b.WriteString("| `" + d.Name + "` | " + cell(d.Label) + " | " + cell(d.Recognises) + " |\n")
	}
	return b.String()
}

// cell keeps a description from breaking out of its table cell.
func cell(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", `\|`), "\n", " ")
}

// TestCredentialPatternsReference regenerates the page with
// -update-credentials, and otherwise fails when the checked-in copy has
// drifted from the registry.
func TestCredentialPatternsReference(t *testing.T) {
	path := filepath.Join(repoRoot(t), credentialPatternsPage)
	want := renderCredentialPatterns()

	if *updateCredentials {
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			t.Fatalf("writing %s: %v", credentialPatternsPage, err)
		}
		t.Logf("regenerated %s (%d detectors)", credentialPatternsPage, len(redact.Detectors()))
		return
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%s is missing: %v\nRegenerate it with: make docs-credentials", credentialPatternsPage, err)
	}
	if string(got) == want {
		return
	}
	var missing []string
	for _, d := range redact.Detectors() {
		if !strings.Contains(string(got), "| `"+d.Name+"` |") {
			missing = append(missing, d.Name)
		}
	}
	t.Errorf("%s is out of date with pkg/redact's registry.\nRegenerate it with: make docs-credentials\n"+
		"Detectors the page does not list: %v (none means a label, a description or the prose differs)",
		credentialPatternsPage, missing)
}
