package docs_test

// docs/reference/http-api.md is generated, not written (Task 20257).
//
// cloop exposes two HTTP APIs and neither had a page. Writing one by hand
// would have documented 149 endpoints accurately for about a week: the hub
// alone grew from 8 routes to 140-odd, and a reference maintained beside a
// route table is a reference that silently falls behind it — which is worse
// than none, because a reader cannot tell a missing endpoint from an absent
// feature.
//
// So the page is rendered from the route tables themselves, by this test, and
// the checked-in copy is compared against a fresh rendering on every run. Add
// a route and this test fails until the page is regenerated:
//
//	make docs-api      # or: go test ./tests/docs -run TestHTTPAPIReference -update
//
// The golden-file shape is deliberate. Generating the page at build time would
// leave it absent from the repository, and the published site is built from
// the tree — so the file has to exist, and the only way an existing file stays
// honest is for something to fail when it stops being.

import (
	"flag"
	"os"
	"path/filepath"

	"strings"
	"testing"

	"github.com/blechschmidt/cloop/pkg/apidoc"
	"github.com/blechschmidt/cloop/pkg/apiserver"
	"github.com/blechschmidt/cloop/pkg/ui"
)

// update rewrites the checked-in page instead of asserting against it.
var update = flag.Bool("update", false, "regenerate docs/reference/http-api.md")

// httpAPIPage is the page's path relative to the repository root.
const httpAPIPage = "docs/reference/http-api.md"

// repoRoot is defined in drift_test.go, in this same package.

// pageIntro is the page's hand-written lead. Prose about what the surfaces are
// and how to authenticate is a human's job; the endpoint tables below it are
// not, and everything after this string is generated.
const pageIntro = `# HTTP API reference

Every endpoint of cloop's two HTTP surfaces, generated from the route tables
that serve them. Do not edit this file: it is rendered by
` + "`tests/docs/http_api_test.go`" + ` from ` + "`pkg/ui`" + ` and ` + "`pkg/apiserver`" + `, and a
CI check fails when it stops matching them. Regenerate with ` + "`make docs-api`" + `.

For the conceptual documentation see the [documentation index](../README.md);
for the roles these permissions belong to see the
[security model](../security/model.md).

## Authentication

The hub accepts two credentials, and which one you use depends on whether a
human is present:

- **API token** — ` + "`Authorization: Bearer cloop_pat_…`" + `. Minted by an admin
  (` + "`POST /api/tokens`" + `, or ` + "`cloop hub token create`" + `), carrying an explicit set of
  roles and an optional project restriction. This is the credential for CI,
  scripts, and anything without a browser.
- **Session cookie** — set by the OIDC login flow and used by the dashboard.

` + "`cloop serve`" + ` is different: it is a single-project daemon with one optional
bearer token and no permission model, so its endpoints are either behind that
token or exempt from it.

## Reading the tables

**Permission** is what a caller must hold to reach the endpoint; it is the same
string the audit trail records and ` + "`/api/me`" + ` reports. **Scope** is what that
permission is evaluated against — and the distinction matters: a project-scoped
grant does **not** satisfy a route scoped ` + "`global`" + `, so a user who can administer
one project still cannot read the fleet.

Endpoints marked ` + "`public`" + ` require no permission. On the hub that does not mean
unauthenticated — the authentication middleware has already run, and only the
login flow, the SPA shell and the static assets bypass it — it means no *role*
is required, because the route either reports the caller's own identity or is
scoped to it by construction.

A path marked *(subtree)* is registered as a prefix and matches everything
beneath it.

The machine-readable form of the hub's table is served live at
` + "`GET /api/openapi.json`" + ` (requires ` + "`project.read`" + `), and ` + "`cloop serve`" + ` publishes its
own at ` + "`GET /openapi.json`" + `.
`

// renderPage builds the reference from both route tables.
func renderPage() string {
	return apidoc.Markdown(pageIntro, []apidoc.Surface{
		{
			Title: "Hub API (`cloop ui`)",
			Intro: "The dashboard and everything an integrator can drive: projects, tasks, runs,\n" +
				"the executor fleet, secrets and grants, audit, and the display-glasses surface.\n" +
				"Generated from `routeTable()` in `pkg/ui/routes.go`.",
			Routes: ui.APIRoutes(),
		},
		{
			Title: "REST daemon API (`cloop serve`)",
			Intro: "A single-project REST daemon, separate from the hub. It has no permission\n" +
				"model: every endpoint except the OpenAPI document is behind the bearer token\n" +
				"when one is configured. Generated from `routeTable()` in\n" +
				"`pkg/apiserver/routes.go`; the OpenAPI document it serves is hand-written and\n" +
				"gated against the same table.",
			Routes: apiserver.APIRoutes(),
		},
	})
}

// TestHTTPAPIReference regenerates the page with -update, and otherwise fails
// when the checked-in copy has drifted from the route tables.
func TestHTTPAPIReference(t *testing.T) {
	path := filepath.Join(repoRoot(t), httpAPIPage)
	want := renderPage()

	if *update {
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			t.Fatalf("writing %s: %v", httpAPIPage, err)
		}
		t.Logf("regenerated %s (%d bytes)", httpAPIPage, len(want))
		return
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%s is missing: %v\nRegenerate it with: make docs-api", httpAPIPage, err)
	}
	if string(got) == want {
		return
	}

	// Name the endpoints that moved rather than dumping two documents: the
	// useful half of this failure is which route was added or removed.
	t.Errorf("%s is out of date with the route tables.\nRegenerate it with: make docs-api\n%s",
		httpAPIPage, describeDiff(string(got), want))
}

// describeDiff summarises the table rows that differ between two renderings.
func describeDiff(got, want string) string {
	rows := func(s string) map[string]bool {
		out := map[string]bool{}
		for _, line := range strings.Split(s, "\n") {
			if strings.HasPrefix(line, "| ") && strings.Contains(line, "`/") {
				out[strings.TrimSpace(line)] = true
			}
		}
		return out
	}
	gotRows, wantRows := rows(got), rows(want)

	var added, removed []string
	for r := range wantRows {
		if !gotRows[r] {
			added = append(added, r)
		}
	}
	for r := range gotRows {
		if !wantRows[r] {
			removed = append(removed, r)
		}
	}

	var b strings.Builder
	if len(added) > 0 {
		b.WriteString("\nRoutes the code has but the page does not:\n")
		for _, r := range added {
			b.WriteString("  " + r + "\n")
		}
	}
	if len(removed) > 0 {
		b.WriteString("\nRoutes the page has but the code does not:\n")
		for _, r := range removed {
			b.WriteString("  " + r + "\n")
		}
	}
	if b.Len() == 0 {
		b.WriteString("\n(The endpoint rows match; the prose or summary text differs.)\n")
	}
	return b.String()
}

// TestHTTPAPIReferenceIsSubstantial guards against the gate above passing
// vacuously — a truncated or emptied page would otherwise match a truncated
// or emptied rendering.
func TestHTTPAPIReferenceIsSubstantial(t *testing.T) {
	hub := ui.APIRoutes()
	daemon := apiserver.APIRoutes()

	if len(hub) < 100 {
		t.Errorf("the hub reports %d routes; it serves well over 100", len(hub))
	}
	if len(daemon) < 5 {
		t.Errorf("the REST daemon reports %d routes; it serves 8", len(daemon))
	}

	page, err := os.ReadFile(filepath.Join(repoRoot(t), httpAPIPage))
	if err != nil {
		t.Fatalf("%s is missing: %v", httpAPIPage, err)
	}
	// Every route must appear as a row, not merely be counted.
	for _, rt := range append(append([]apidoc.Route{}, hub...), daemon...) {
		if !strings.Contains(string(page), "`"+rt.Path+"`") {
			t.Errorf("%s does not mention %s %s", httpAPIPage, rt.Method, rt.Path)
		}
	}
}
