// Package taskreplay implements a deterministic task replay harness.
//
// The harness re-executes the prompt that was previously sent for a completed
// task against a different provider/model combination, then compares the
// replayed output against the original. Two comparison signals are produced:
//
//   - SimilarityScore: Jaccard token overlap (0.0–1.0) between the two
//     outputs. Cheap, deterministic, and language-agnostic.
//   - EquivalenceScore (optional): a 1–10 verdict from a judge provider that
//     reads both outputs and rates them for semantic equivalence. Skipped
//     when no judge is supplied.
//
// Each replay is appended as a row in the replay_runs table so the Web UI
// and CLI can browse history without re-executing.
//
// The replay is "deterministic" in the input dimension — the prompt and
// task context are reconstructed from saved state, not regenerated by the
// AI — but the target provider's response is, of course, subject to the
// usual model non-determinism.
package taskreplay

import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"
	"unicode"

	"github.com/blechschmidt/cloop/pkg/artifact"
	"github.com/blechschmidt/cloop/pkg/pm"
	"github.com/blechschmidt/cloop/pkg/provider"
	"github.com/blechschmidt/cloop/pkg/state"
	"github.com/blechschmidt/cloop/pkg/statedb"
)

// ErrTaskNotReplayable is returned when the requested task cannot be replayed
// because it never completed or has no recoverable output.
var ErrTaskNotReplayable = errors.New("task is not replayable: must be done/failed and have recorded output")

// ErrNoTargetProvider is returned when the target provider is not configured.
var ErrNoTargetProvider = errors.New("target provider must be supplied")

// Options controls a single replay invocation.
type Options struct {
	// Target is the provider being compared against (required).
	Target provider.Provider
	// TargetName is the registered name of the target provider (e.g. "anthropic").
	TargetName string
	// TargetModel is the model identifier (empty = provider default).
	TargetModel string
	// MaxTokens for the target completion (0 = provider default).
	MaxTokens int
	// Timeout caps the target completion call (0 = 5 minutes).
	Timeout time.Duration

	// Judge, when non-nil, is asked to rate semantic equivalence on a 1–10 scale.
	// The judge is typically a strong general-purpose model (e.g. claude-opus).
	// When nil, EquivalenceScore is left at 0 and EquivalenceRationale is empty.
	Judge      provider.Provider
	JudgeModel string
}

// Result captures the outcome of one replay against a single task.
type Result struct {
	TaskID               int
	TaskTitle            string
	OriginalProvider     string
	OriginalModel        string
	TargetProvider       string
	TargetModel          string
	Prompt               string
	OriginalOutput       string
	ReplayedOutput       string
	SimilarityScore      float64 // Jaccard 0.0–1.0
	EquivalenceScore     int     // 0 = not judged, 1–10 = AI verdict
	EquivalenceRationale string
	Duration             time.Duration
	InputTokens          int
	OutputTokens         int
	Err                  string // non-empty on failure (still persisted for visibility)
	CreatedAt            time.Time
}

// ReplayTask reconstructs the prompt for a completed task, re-executes it
// against opts.Target, computes a Jaccard similarity score against the
// original output, optionally calls opts.Judge for a 1–10 equivalence verdict,
// and persists the comparison to the replay_runs table.
//
// On hard failure (target call errors, judge errors) the function still
// returns a partially-populated *Result with Err set so callers can persist
// the attempt.
func ReplayTask(ctx context.Context, workDir string, taskID int, opts Options) (*Result, error) {
	if opts.Target == nil {
		return nil, ErrNoTargetProvider
	}

	s, err := state.Load(workDir)
	if err != nil {
		return nil, fmt.Errorf("load state: %w", err)
	}
	if s.Plan == nil || len(s.Plan.Tasks) == 0 {
		return nil, fmt.Errorf("no plan found in %s: %w", workDir, ErrTaskNotReplayable)
	}

	task := s.Plan.TaskByID(taskID)
	if task == nil {
		return nil, fmt.Errorf("task %d not found: %w", taskID, statedb.ErrTaskNotFound)
	}
	if !isReplayable(task) {
		return nil, fmt.Errorf("task %d (status=%s): %w", taskID, task.Status, ErrTaskNotReplayable)
	}

	originalOutput := artifact.ReadTaskOutput(workDir, task)
	if strings.TrimSpace(originalOutput) == "" {
		return nil, fmt.Errorf("task %d has no recorded output: %w", taskID, ErrTaskNotReplayable)
	}

	// Reconstruct the prompt deterministically from the (current) plan + task.
	// Note: this is the prompt that *would* be sent today, not the byte-exact
	// prompt sent originally. That is acceptable for regression testing — the
	// goal is "would today's plan, on this provider, produce equivalent
	// output?" not byte-exact replay.
	prompt := pm.ExecuteTaskPrompt(s.Plan.Goal, s.Instructions, "", s.Plan, task, true)

	timeout := opts.Timeout
	if timeout <= 0 {
		timeout = 5 * time.Minute
	}
	maxTokens := opts.MaxTokens
	if maxTokens <= 0 {
		maxTokens = 4096
	}

	res := &Result{
		TaskID:           task.ID,
		TaskTitle:        task.Title,
		OriginalProvider: s.Provider,
		OriginalModel:    s.Model,
		TargetProvider:   opts.TargetName,
		TargetModel:      opts.TargetModel,
		Prompt:           prompt,
		OriginalOutput:   originalOutput,
		CreatedAt:        time.Now(),
	}

	callCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	start := time.Now()
	out, callErr := opts.Target.Complete(callCtx, prompt, provider.Options{
		Model:     opts.TargetModel,
		MaxTokens: maxTokens,
		Timeout:   timeout,
	})
	res.Duration = time.Since(start)

	if callErr != nil {
		res.Err = callErr.Error()
	} else if out != nil {
		res.ReplayedOutput = out.Output
		res.InputTokens = out.InputTokens
		res.OutputTokens = out.OutputTokens
		if res.TargetModel == "" {
			res.TargetModel = out.Model
		}
		if res.TargetProvider == "" {
			res.TargetProvider = out.Provider
		}
	}

	// Compute similarity even on partial output — empty strings score 0.0.
	res.SimilarityScore = JaccardSimilarity(originalOutput, res.ReplayedOutput)

	// Optional AI judge: skipped on call failure (no replayed output) and when
	// no judge provider was configured.
	if opts.Judge != nil && res.ReplayedOutput != "" {
		score, rationale, jerr := judgeEquivalence(ctx, opts.Judge, opts.JudgeModel, task, originalOutput, res.ReplayedOutput)
		if jerr != nil {
			// Don't fail the whole replay because the judge tripped — record
			// in Err only when the primary call also failed.
			if res.Err == "" {
				res.Err = "judge failed: " + jerr.Error()
			}
		} else {
			res.EquivalenceScore = score
			res.EquivalenceRationale = rationale
		}
	}

	if err := persistReplay(workDir, res); err != nil {
		return res, fmt.Errorf("persist replay: %w", err)
	}
	return res, nil
}

// isReplayable returns true when a task is in a state worth replaying.
// We allow done, failed, skipped, and timed_out — anything that was actually
// executed and might have output. Pending and in_progress are rejected.
func isReplayable(t *pm.Task) bool {
	switch t.Status {
	case pm.TaskDone, pm.TaskFailed, pm.TaskSkipped, pm.TaskTimedOut:
		return true
	default:
		return false
	}
}

// JaccardSimilarity returns the Jaccard token-overlap coefficient between two
// strings (0.0 = no overlap, 1.0 = identical token sets). Both inputs are
// lowercased and split on Unicode whitespace and punctuation. Returns 0.0
// when either input has no tokens.
func JaccardSimilarity(a, b string) float64 {
	ta := tokenize(a)
	tb := tokenize(b)
	if len(ta) == 0 || len(tb) == 0 {
		return 0
	}
	setA := make(map[string]struct{}, len(ta))
	for _, t := range ta {
		setA[t] = struct{}{}
	}
	setB := make(map[string]struct{}, len(tb))
	for _, t := range tb {
		setB[t] = struct{}{}
	}
	intersect := 0
	for t := range setA {
		if _, ok := setB[t]; ok {
			intersect++
		}
	}
	union := len(setA) + len(setB) - intersect
	if union == 0 {
		return 0
	}
	score := float64(intersect) / float64(union)
	if math.IsNaN(score) || math.IsInf(score, 0) {
		return 0
	}
	return score
}

// tokenize lowercases s and splits it into tokens at any non-letter/digit
// rune. Used for Jaccard similarity. Empty tokens are filtered.
func tokenize(s string) []string {
	if s == "" {
		return nil
	}
	out := make([]string, 0, 64)
	var b strings.Builder
	flush := func() {
		if b.Len() > 0 {
			out = append(out, b.String())
			b.Reset()
		}
	}
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToLower(r))
		} else {
			flush()
		}
	}
	flush()
	return out
}

// judgePrompt builds the prompt used to ask an AI judge for an equivalence
// verdict. The judge is asked for a single integer (1–10) plus a one-sentence
// rationale, returned in a parsable format.
func judgePrompt(task *pm.Task, original, replayed string) string {
	var b strings.Builder
	b.WriteString("You are a strict but fair AI evaluator. Two AI models were asked to do the same task. ")
	b.WriteString("Compare the OUTCOMES — not surface similarity — for whether they accomplished the task equivalently.\n\n")
	b.WriteString("Task title: ")
	b.WriteString(task.Title)
	b.WriteString("\n")
	if task.Description != "" {
		b.WriteString("Task description: ")
		b.WriteString(task.Description)
		b.WriteString("\n")
	}
	b.WriteString("\n--- ORIGINAL OUTPUT ---\n")
	b.WriteString(clamp(original, 8000))
	b.WriteString("\n--- REPLAYED OUTPUT ---\n")
	b.WriteString(clamp(replayed, 8000))
	b.WriteString("\n--- END ---\n\n")
	b.WriteString("Reply on EXACTLY two lines:\n")
	b.WriteString("Line 1: an integer 1-10 (10 = fully equivalent outcomes; 1 = completely different).\n")
	b.WriteString("Line 2: a one-sentence rationale.\n")
	return b.String()
}

// judgeEquivalence calls the judge provider and parses the reply.
func judgeEquivalence(ctx context.Context, judge provider.Provider, model string, task *pm.Task, original, replayed string) (int, string, error) {
	if judge == nil {
		return 0, "", nil
	}
	jctx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()
	res, err := judge.Complete(jctx, judgePrompt(task, original, replayed), provider.Options{
		Model:     model,
		MaxTokens: 256,
		Timeout:   60 * time.Second,
	})
	if err != nil {
		return 0, "", err
	}
	if res == nil {
		return 0, "", errors.New("judge returned nil result")
	}
	score, rationale := parseJudgeReply(res.Output)
	return score, rationale, nil
}

// parseJudgeReply extracts the score and rationale from the judge's response.
// The expected format is "<int>\n<rationale>"; we are tolerant of extra
// whitespace and stray prefixes.
func parseJudgeReply(out string) (int, string) {
	out = strings.TrimSpace(out)
	if out == "" {
		return 0, ""
	}
	lines := strings.SplitN(out, "\n", 2)
	scoreStr := strings.TrimSpace(lines[0])
	scoreStr = strings.TrimPrefix(scoreStr, "Score:")
	scoreStr = strings.TrimPrefix(scoreStr, "score:")
	scoreStr = strings.TrimSpace(scoreStr)
	scoreStr = strings.SplitN(scoreStr, "/", 2)[0]
	scoreStr = strings.TrimRight(scoreStr, ".,;: ")
	score := 0
	for _, r := range scoreStr {
		if r >= '0' && r <= '9' {
			score = score*10 + int(r-'0')
		} else {
			break
		}
	}
	if score < 1 || score > 10 {
		score = 0
	}
	rationale := ""
	if len(lines) == 2 {
		rationale = strings.TrimSpace(lines[1])
	}
	return score, rationale
}

// clamp truncates s to at most n runes, appending an ellipsis marker.
func clamp(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "\n[...truncated...]"
}
