package secretbroker

// githubguarded.go is the delivery half of gitguard.go: what a lease directory
// contains once a PAT is held by a proxy rather than by the workload.
//
// The shape deliberately mirrors the unguarded delivery in githubpat.go — a
// gitconfig, a credential helper, and a file holding the secret — because the
// workload should not be able to tell the difference. git is configured, git
// asks for a credential, git gets one. What changed is which credential, and
// what it is worth: a session token bound to one proxy, one allowlist, one ref
// policy and one TTL, instead of a personal access token bound to nothing.

import (
	"crypto/subtle"
	"fmt"
	"net/url"
	"strings"
)

// buildProxyGitConfig returns a git configuration that routes every GitHub
// remote through the proxy and authenticates to it with the session
// credential.
//
// The rewriting is what makes this transparent. A workload that was told to
// clone https://github.com/acme/tool — by a task description, by a checked-in
// submodule, by `go get` — reaches the proxy instead, without knowing the
// proxy exists. Nothing in the sandbox has to opt in, which matters because
// the workload is precisely the party whose cooperation cannot be assumed.
//
// The ssh forms are rewritten too. Not because the sandbox has a key — it does
// not, and an ssh remote would simply fail — but because failing is the wrong
// outcome when a working path exists: a repository referenced as
// git@github.com:acme/tool is one the grant may well allow, and routing it to
// the proxy turns a dead end into an authorised fetch.
func buildProxyGitConfig(baseURL string) (string, error) {
	base, err := normalizeProxyBase(baseURL)
	if err != nil {
		return "", err
	}
	// Config values are quoted and the base has been parsed as a URL and
	// re-rendered from its scheme and host, so it cannot carry a newline that
	// would forge a second directive.
	var b strings.Builder
	b.WriteString("# Generated by cloop secretbroker for the lifetime of one lease.\n")
	b.WriteString("# GitHub is reached through cloop's git proxy, which holds the\n")
	b.WriteString("# credential and enforces this grant's repository allowlist and\n")
	b.WriteString("# ref policy. The token itself is not present in this sandbox.\n")
	b.WriteString("[credential]\n")
	b.WriteString("\tuseHttpPath = true\n")
	b.WriteString("\thelper = !\"$CLOOP_LEASE_DIR/" + credentialHelperName + "\"\n")
	b.WriteString("[url \"" + base + "/\"]\n")
	b.WriteString("\tinsteadOf = https://" + githubHost + "/\n")
	b.WriteString("\tinsteadOf = git@" + githubHost + ":\n")
	b.WriteString("\tinsteadOf = ssh://git@" + githubHost + "/\n")
	return b.String(), nil
}

// buildProxyCredentialHelper generates a POSIX sh helper that releases the
// session credential for the proxy's own host and nothing else.
//
// The host check is not defence of the session token, which is useless
// elsewhere. It is defence of the *rewriting*: a helper that answered for any
// host would answer for github.com directly, and a workload that set its own
// remote back to github.com would get a credential that fails there — an
// obscure authentication error instead of the proxy refusal that explains
// itself. Silence for unknown hosts keeps git's own "could not read
// Username" as the outcome, which is the message that leads somewhere.
func buildProxyCredentialHelper(baseURL string) (string, error) {
	base, err := normalizeProxyBase(baseURL)
	if err != nil {
		return "", err
	}
	u, err := url.Parse(base)
	if err != nil {
		return "", fmt.Errorf("secretbroker: proxy base %q is not a URL: %w", baseURL, err)
	}
	host := u.Host
	// Git's credential protocol reports the host with its port when the URL
	// carries one, so the value compared here is whatever the rewritten URL
	// produced. Validated rather than trusted: a host reaching the script body
	// is the one place a crafted base could inject shell.
	if err := validateShellSafeHost(host); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by cloop secretbroker. Releases a cloop git proxy session\n")
	b.WriteString("# credential for the proxy host only. Do not edit.\n")
	b.WriteString("set -u\n")
	b.WriteString("[ \"${1:-}\" = get ] || exit 0\n")
	b.WriteString("dir=$(dirname \"$0\")\n")
	b.WriteString("proto=; host=\n")
	b.WriteString("while IFS='=' read -r key value; do\n")
	b.WriteString("  case \"$key\" in\n")
	b.WriteString("    protocol) proto=$value ;;\n")
	b.WriteString("    host) host=$value ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("done\n")
	b.WriteString("[ \"$proto\" = https ] || exit 0\n")
	b.WriteString("[ \"$host\" = " + host + " ] || exit 0\n")
	b.WriteString("[ -r \"$dir/" + proxyCredentialName + "\" ] || exit 0\n")
	// The file already holds git's own key=value lines, so the helper emits it
	// verbatim rather than reassembling a credential it would have to quote.
	b.WriteString("cat \"$dir/" + proxyCredentialName + "\"\n")
	return b.String(), nil
}

// normalizeProxyBase renders the proxy base as scheme://host with no path, and
// rejects anything that is not an https URL. Re-rendering from the parsed parts
// is what guarantees the value written into a config file is a URL and not an
// arbitrary string that happened to arrive in a URL-shaped field.
func normalizeProxyBase(raw string) (string, error) {
	s := strings.TrimSpace(raw)
	if s == "" {
		return "", fmt.Errorf("secretbroker: git proxy base URL is empty")
	}
	u, err := url.Parse(s)
	if err != nil {
		return "", fmt.Errorf("secretbroker: git proxy base %q is not a URL: %w", raw, err)
	}
	switch {
	case u.Scheme != "https":
		return "", fmt.Errorf("secretbroker: git proxy base must be https, got scheme %q", u.Scheme)
	case u.Host == "":
		return "", fmt.Errorf("secretbroker: git proxy base %q has no host", raw)
	case u.User != nil:
		return "", fmt.Errorf("secretbroker: git proxy base must not embed credentials")
	case strings.Trim(u.Path, "/") != "":
		return "", fmt.Errorf("secretbroker: git proxy base must have no path, got %q", u.Path)
	}
	// The charset is checked here rather than only where the host is spliced
	// into the shell helper, because this function also feeds the *gitconfig*,
	// where the base is written inside a quoted section header. url.Parse
	// accepts `"`, `<`, `>`, `$`, `;` and `'` in a host, so a base of
	// https://ex"ample.com would render [url "https://ex"ample.com/"] and break
	// the quoting. It happened to fail closed only because deliverGuardedGitHub
	// also builds the helper, whose own check rejects it — an unstated coupling
	// that the next caller of this function would not inherit.
	if err := validateShellSafeHost(u.Host); err != nil {
		return "", err
	}
	return u.Scheme + "://" + u.Host, nil
}

// validateShellSafeHost rejects a host that could not appear unquoted in the
// generated helper. The charset is deliberately narrower than what a URL host
// may contain: this is a gate, not a parser, and a host outside it is a
// configuration mistake rather than a case to support.
func validateShellSafeHost(host string) error {
	if host == "" {
		return fmt.Errorf("secretbroker: git proxy host is empty")
	}
	for _, r := range host {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '.' || r == '-' || r == ':' || r == '_':
		case r == '[' || r == ']':
			// An IPv6 literal arrives bracketed. Harmless in the `[ x = y ]`
			// comparison the helper uses, since the value is a single word.
		default:
			return fmt.Errorf("secretbroker: git proxy host %q contains an unusable character %q", host, r)
		}
	}
	return nil
}

// deliverGuardedGitHub builds the lease files for a PAT the proxy holds.
//
// The contrast with deliverGitHubToken is the whole feature: no token file is
// written, GITHUB_TOKEN is not exported under any allowlist, and the only
// credential in the sandbox is one the proxy issued and can revoke.
func deliverGuardedGitHub(mat Material, res GitGuardResult) (Material, error) {
	if !res.Guarded() {
		return Material{}, fmt.Errorf("%w: guard returned no credential for %s",
			ErrGuardUnavailable, mat.SecretName)
	}
	if strings.TrimSpace(res.Username) == "" {
		return Material{}, fmt.Errorf("%w: guard returned no username for %s",
			ErrGuardUnavailable, mat.SecretName)
	}
	// A guard that handed back the very token it was given would silently undo
	// the whole exchange, and the result would look identical to a working one
	// from every angle except the security property. Cheap to check, and the
	// only place with both values in hand.
	//
	// ConstantTimeCompare rather than ==, because both operands are
	// credentials. Nothing here is remotely timed — this runs once while a
	// lease is being built — but tests/security refuses a byte-wise == on
	// credential-shaped values across the whole tree, and a local exemption
	// would be the start of not having that rule.
	if mat.githubToken != "" &&
		subtle.ConstantTimeCompare([]byte(res.Password), []byte(mat.githubToken)) == 1 {
		return Material{}, fmt.Errorf("%w: guard returned the unguarded token for %s",
			ErrGuardUnavailable, mat.SecretName)
	}
	if strings.ContainsAny(res.Username+res.Password, "\n\r") {
		return Material{}, fmt.Errorf("%w: guard credential for %s contains a newline",
			ErrGuardUnavailable, mat.SecretName)
	}

	gitconfig, err := buildProxyGitConfig(res.BaseURL)
	if err != nil {
		return Material{}, err
	}
	helper, err := buildProxyCredentialHelper(res.BaseURL)
	if err != nil {
		return Material{}, err
	}

	cred := "username=" + res.Username + "\npassword=" + res.Password + "\n"
	mat.Files = []File{
		{Name: proxyCredentialName, Content: []byte(cred), Mode: 0o600},
		{Name: credentialHelperName, Content: []byte(helper), Mode: 0o700},
		{
			Name:    gitconfigName,
			Content: []byte(gitconfig),
			Mode:    0o600,
			EnvVar:  "GIT_CONFIG_GLOBAL",
		},
	}

	mat.Env["CLOOP_GITHUB_REPO_ALLOWLIST"] = strings.Join(mat.Constraints.Repos, ",")
	if len(mat.Constraints.Permissions) > 0 {
		mat.Env["CLOOP_GITHUB_PERMISSIONS"] = strings.Join(mat.Constraints.Permissions, ",")
	}
	// Announced so a workload — and a human reading a failed run — can tell
	// the difference between "this grant has no write permission" and "this
	// repository is outside the allowlist" without guessing from a git error.
	// None of these is a credential; none is added to SensitiveEnv.
	mat.Env["CLOOP_GIT_PROXY_URL"] = res.BaseURL
	mat.Env[GitProxySessionEnvKey] = res.SessionID
	if res.ReadOnly {
		mat.Env["CLOOP_GIT_PROXY_MODE"] = "read-only"
	} else {
		mat.Env["CLOOP_GIT_PROXY_MODE"] = "read-write"
	}
	return mat, nil
}
