package secretbroker

import (
	"strings"
)

// GitHub's canonical host. Credentials are released for this host only; a
// grant for github.com must not authenticate to a look-alike that a
// workload's /etc/hosts or proxy points elsewhere.
const githubHost = "github.com"

// credentialHelperName is the file the generated helper is written to inside
// the lease's tmpfs directory.
const credentialHelperName = "git-credential-cloop"

// tokenFileName holds the raw token, read by the helper at use time. Keeping
// it out of the script body matters: a script is the sort of thing that ends
// up in a `set -x` trace or a debug dump of the lease directory, and a token
// baked into its text would go with it.
const tokenFileName = "github-token"

// gitconfigName is the git configuration that installs the helper.
const gitconfigName = "gitconfig"

// buildGitCredentialHelper generates a POSIX sh credential helper that
// releases the token only for repositories inside the allowlist.
//
// Why a script at all: GitHub offers no way to narrow an already-issued PAT,
// so "this token may only touch org/*" cannot be enforced by reshaping the
// credential the way a kubeconfig can. The next best enforcement point is
// the moment git asks for it. Git's credential protocol supplies the
// repository path when credential.useHttpPath is on, so the helper can
// answer for org/tool and stay silent for someone-else/private — and a
// workload that never receives the token for a repository cannot use it
// there, regardless of what it intended.
//
// Injection safety: every pattern reaching this function has already passed
// validatePattern, whose charset excludes quotes, backticks, dollar signs,
// backslashes, newlines, and semicolons. We re-check here anyway rather than
// trusting that the database we read from was written by a version of this
// code with that check in it.
//
// Matching parity with Constraints.AllowsRepo is deliberate and load-bearing:
// the helper first rejects any path that is not exactly owner/name, which
// makes shell `case` globbing — where "*" happily crosses "/" — agree with
// path.Match, where it does not. Without that guard "org/*" would mean two
// different things in the two matchers, and the shell's would be the wider.
func buildGitCredentialHelper(patterns []string) (string, error) {
	cases := make([]string, 0, len(patterns))
	allowAll := false
	for _, p := range patterns {
		if err := validatePattern("repos", p); err != nil {
			return "", err
		}
		lowered := strings.ToLower(strings.TrimSuffix(strings.Trim(p, "/"), ".git"))
		if lowered == "*" || lowered == "*/*" {
			allowAll = true
		}
		cases = append(cases, lowered)
	}
	if allowAll {
		// Collapse to a single pattern that the single-slash guard above
		// still constrains to owner/name.
		cases = []string{"*/*"}
	}

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by cloop secretbroker. Releases a GitHub token only for\n")
	b.WriteString("# repositories inside the grant's allowlist. Do not edit.\n")
	b.WriteString("set -u\n")
	b.WriteString("[ \"${1:-}\" = get ] || exit 0\n")
	b.WriteString("dir=$(dirname \"$0\")\n")
	b.WriteString("proto=; host=; reqpath=\n")
	// Read git's key=value request from stdin. An unrecognised key is
	// ignored, which is what the credential protocol requires.
	b.WriteString("while IFS='=' read -r key value; do\n")
	b.WriteString("  case \"$key\" in\n")
	b.WriteString("    protocol) proto=$value ;;\n")
	b.WriteString("    host) host=$value ;;\n")
	b.WriteString("    path) reqpath=$value ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("done\n")
	// Only https to the real github.com. Anything else gets silence.
	b.WriteString("[ \"$proto\" = https ] || exit 0\n")
	b.WriteString("[ \"$host\" = " + githubHost + " ] || exit 0\n")
	b.WriteString("[ -n \"$reqpath\" ] || exit 0\n")
	// Normalise: strip a leading slash and a .git suffix, then lowercase.
	// If tr is missing the comparison stays cased and simply fails to
	// match — the safe direction, since a non-match releases nothing.
	b.WriteString("repo=${reqpath#/}\n")
	b.WriteString("repo=${repo%.git}\n")
	b.WriteString("repo=$(printf '%s' \"$repo\" | tr 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' 'abcdefghijklmnopqrstuvwxyz' 2>/dev/null || printf '%s' \"$repo\")\n")
	// Exactly one slash: this is what makes shell globbing agree with
	// path.Match's non-separator-crossing "*".
	b.WriteString("case \"$repo\" in\n")
	b.WriteString("  */*/*) exit 0 ;;\n")
	b.WriteString("  */*) ;;\n")
	b.WriteString("  *) exit 0 ;;\n")
	b.WriteString("esac\n")
	b.WriteString("case \"$repo\" in\n")
	b.WriteString("  " + strings.Join(cases, "|") + ") ;;\n")
	b.WriteString("  *) exit 0 ;;\n")
	b.WriteString("esac\n")
	b.WriteString("[ -r \"$dir/" + tokenFileName + "\" ] || exit 0\n")
	b.WriteString("printf 'username=x-access-token\\n'\n")
	b.WriteString("printf 'password=%s\\n' \"$(cat \"$dir/" + tokenFileName + "\")\"\n")
	return b.String(), nil
}

// buildGitConfig returns a git configuration file that installs the helper
// and turns on useHttpPath, without which git would not tell the helper
// which repository it is authenticating for — and the allowlist would have
// nothing to match against.
//
// The helper is referenced through $CLOOP_LEASE_DIR rather than an absolute
// path because the config is built before the lease directory exists, and
// because a remote executor materialises the lease at a path the control
// plane never learns. The "!" prefix is what makes git run the value through
// a shell, which is what expands the variable; git appends the operation, so
// the script still receives "get" as $1.
//
// It is delivered via GIT_CONFIG_GLOBAL so it applies to the workload
// without touching any real ~/.gitconfig, and evaporates with the lease.
func buildGitConfig() string {
	var b strings.Builder
	b.WriteString("# Generated by cloop secretbroker for the lifetime of one lease.\n")
	b.WriteString("[credential]\n")
	b.WriteString("\tuseHttpPath = true\n")
	b.WriteString("\thelper = !\"$CLOOP_LEASE_DIR/" + credentialHelperName + "\"\n")
	return b.String()
}

// GitHubToken returns the raw token a GitHub material carries, and whether it
// carries one at all.
//
// It exists because workspace provisioning (pkg/executor/gitcreds) needs the
// token as an HTTP basic password, and the two paths that already deliver it —
// the credential-helper script and the bare GITHUB_TOKEN env var — are both
// wrong for that use. The helper needs a shell and a materialised lease
// directory, which is exactly the disk write a sandbox fetch must avoid; and
// GITHUB_TOKEN is only exported for an unrestricted "*" grant, so relying on it
// would make narrow grants silently unable to clone.
//
// Reading the token out of Files rather than re-deriving it keeps one source of
// truth: whatever githubMaterial decided to deliver is what a caller sees. The
// returned string is the caller's to handle carefully — it is a credential, and
// nothing here can stop it being logged.
func (m Material) GitHubToken() (string, bool) {
	switch m.Kind {
	case KindGitHubPAT, KindGitHubApp:
	default:
		return "", false
	}
	for _, f := range m.Files {
		if f.Name != tokenFileName {
			continue
		}
		token := strings.TrimSpace(string(f.Content))
		if token == "" {
			return "", false
		}
		return token, true
	}
	return "", false
}

// GitHubUsername is the basic-auth username GitHub expects alongside a PAT.
// GitHub ignores the value for a PAT but requires a non-empty one, and
// "x-access-token" is the name its own tooling uses.
const GitHubUsername = "x-access-token"

// allowsAllRepos reports whether the allowlist is an unrestricted wildcard.
//
// This gates whether a bare GITHUB_TOKEN environment variable is exported.
// An env var is unscoped by construction — every tool in the workload reads
// it and uses it against any repository — so it is only honest to export one
// when the operator has explicitly said "all repositories". For a narrower
// grant the credential helper is the only delivery path, which is the whole
// difference between an enforced allowlist and a documented one.
func allowsAllRepos(patterns []string) bool {
	for _, p := range patterns {
		switch strings.ToLower(strings.TrimSpace(p)) {
		case "*", "*/*":
			return true
		}
	}
	return false
}
